/*
PlainRouter Conversion API

PlainRouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plainrouter

import (
	"encoding/json"
	"fmt"
)

// checks if the GetEvent200ResponseLineageChildrenInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEvent200ResponseLineageChildrenInner{}

// GetEvent200ResponseLineageChildrenInner struct for GetEvent200ResponseLineageChildrenInner
type GetEvent200ResponseLineageChildrenInner struct {
	Id                          string         `json:"id"`
	SignalTrackerId             string         `json:"signal_tracker_id"`
	ParentEventId               NullableString `json:"parent_event_id"`
	EventName                   string         `json:"event_name"`
	EventTime                   string         `json:"event_time"`
	ActionSource                string         `json:"action_source"`
	EventClass                  string         `json:"event_class"`
	OrderId                     NullableString `json:"order_id"`
	ValueAmount                 NullableInt32  `json:"value_amount"`
	ValueCurrency               NullableString `json:"value_currency"`
	CreatedAt                   string         `json:"created_at"`
	ConsentBasis                string         `json:"consent_basis"`
	MeasurementClass            string         `json:"measurement_class"`
	AttributionJoin             string         `json:"attribution_join"`
	EnforcementScope            string         `json:"enforcement_scope"`
	ConsentNormalizationVersion string         `json:"consent_normalization_version"`
	Consent                     interface{}    `json:"consent"`
	UserDataHashed              interface{}    `json:"user_data_hashed"`
	ClickIds                    interface{}    `json:"click_ids"`
	Session                     interface{}    `json:"session"`
	ValueData                   interface{}    `json:"value_data"`
	EventSource                 NullableString `json:"event_source"`
	PayloadExpired              bool           `json:"payload_expired"`
	AdditionalProperties        map[string]interface{}
}

type _GetEvent200ResponseLineageChildrenInner GetEvent200ResponseLineageChildrenInner

// NewGetEvent200ResponseLineageChildrenInner instantiates a new GetEvent200ResponseLineageChildrenInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEvent200ResponseLineageChildrenInner(id string, signalTrackerId string, parentEventId NullableString, eventName string, eventTime string, actionSource string, eventClass string, orderId NullableString, valueAmount NullableInt32, valueCurrency NullableString, createdAt string, consentBasis string, measurementClass string, attributionJoin string, enforcementScope string, consentNormalizationVersion string, consent interface{}, userDataHashed interface{}, clickIds interface{}, session interface{}, valueData interface{}, eventSource NullableString, payloadExpired bool) *GetEvent200ResponseLineageChildrenInner {
	this := GetEvent200ResponseLineageChildrenInner{}
	this.Id = id
	this.SignalTrackerId = signalTrackerId
	this.ParentEventId = parentEventId
	this.EventName = eventName
	this.EventTime = eventTime
	this.ActionSource = actionSource
	this.EventClass = eventClass
	this.OrderId = orderId
	this.ValueAmount = valueAmount
	this.ValueCurrency = valueCurrency
	this.CreatedAt = createdAt
	this.ConsentBasis = consentBasis
	this.MeasurementClass = measurementClass
	this.AttributionJoin = attributionJoin
	this.EnforcementScope = enforcementScope
	this.ConsentNormalizationVersion = consentNormalizationVersion
	this.Consent = consent
	this.UserDataHashed = userDataHashed
	this.ClickIds = clickIds
	this.Session = session
	this.ValueData = valueData
	this.EventSource = eventSource
	this.PayloadExpired = payloadExpired
	return &this
}

// NewGetEvent200ResponseLineageChildrenInnerWithDefaults instantiates a new GetEvent200ResponseLineageChildrenInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEvent200ResponseLineageChildrenInnerWithDefaults() *GetEvent200ResponseLineageChildrenInner {
	this := GetEvent200ResponseLineageChildrenInner{}
	return &this
}

// GetId returns the Id field value
func (o *GetEvent200ResponseLineageChildrenInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetEvent200ResponseLineageChildrenInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetEvent200ResponseLineageChildrenInner) SetId(v string) {
	o.Id = v
}

// GetSignalTrackerId returns the SignalTrackerId field value
func (o *GetEvent200ResponseLineageChildrenInner) GetSignalTrackerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SignalTrackerId
}

// GetSignalTrackerIdOk returns a tuple with the SignalTrackerId field value
// and a boolean to check if the value has been set.
func (o *GetEvent200ResponseLineageChildrenInner) GetSignalTrackerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SignalTrackerId, true
}

// SetSignalTrackerId sets field value
func (o *GetEvent200ResponseLineageChildrenInner) SetSignalTrackerId(v string) {
	o.SignalTrackerId = v
}

// GetParentEventId returns the ParentEventId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetEvent200ResponseLineageChildrenInner) GetParentEventId() string {
	if o == nil || o.ParentEventId.Get() == nil {
		var ret string
		return ret
	}

	return *o.ParentEventId.Get()
}

// GetParentEventIdOk returns a tuple with the ParentEventId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetEvent200ResponseLineageChildrenInner) GetParentEventIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentEventId.Get(), o.ParentEventId.IsSet()
}

// SetParentEventId sets field value
func (o *GetEvent200ResponseLineageChildrenInner) SetParentEventId(v string) {
	o.ParentEventId.Set(&v)
}

// GetEventName returns the EventName field value
func (o *GetEvent200ResponseLineageChildrenInner) GetEventName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventName
}

// GetEventNameOk returns a tuple with the EventName field value
// and a boolean to check if the value has been set.
func (o *GetEvent200ResponseLineageChildrenInner) GetEventNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventName, true
}

// SetEventName sets field value
func (o *GetEvent200ResponseLineageChildrenInner) SetEventName(v string) {
	o.EventName = v
}

// GetEventTime returns the EventTime field value
func (o *GetEvent200ResponseLineageChildrenInner) GetEventTime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventTime
}

// GetEventTimeOk returns a tuple with the EventTime field value
// and a boolean to check if the value has been set.
func (o *GetEvent200ResponseLineageChildrenInner) GetEventTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventTime, true
}

// SetEventTime sets field value
func (o *GetEvent200ResponseLineageChildrenInner) SetEventTime(v string) {
	o.EventTime = v
}

// GetActionSource returns the ActionSource field value
func (o *GetEvent200ResponseLineageChildrenInner) GetActionSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ActionSource
}

// GetActionSourceOk returns a tuple with the ActionSource field value
// and a boolean to check if the value has been set.
func (o *GetEvent200ResponseLineageChildrenInner) GetActionSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActionSource, true
}

// SetActionSource sets field value
func (o *GetEvent200ResponseLineageChildrenInner) SetActionSource(v string) {
	o.ActionSource = v
}

// GetEventClass returns the EventClass field value
func (o *GetEvent200ResponseLineageChildrenInner) GetEventClass() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventClass
}

// GetEventClassOk returns a tuple with the EventClass field value
// and a boolean to check if the value has been set.
func (o *GetEvent200ResponseLineageChildrenInner) GetEventClassOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventClass, true
}

// SetEventClass sets field value
func (o *GetEvent200ResponseLineageChildrenInner) SetEventClass(v string) {
	o.EventClass = v
}

// GetOrderId returns the OrderId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetEvent200ResponseLineageChildrenInner) GetOrderId() string {
	if o == nil || o.OrderId.Get() == nil {
		var ret string
		return ret
	}

	return *o.OrderId.Get()
}

// GetOrderIdOk returns a tuple with the OrderId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetEvent200ResponseLineageChildrenInner) GetOrderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrderId.Get(), o.OrderId.IsSet()
}

// SetOrderId sets field value
func (o *GetEvent200ResponseLineageChildrenInner) SetOrderId(v string) {
	o.OrderId.Set(&v)
}

// GetValueAmount returns the ValueAmount field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *GetEvent200ResponseLineageChildrenInner) GetValueAmount() int32 {
	if o == nil || o.ValueAmount.Get() == nil {
		var ret int32
		return ret
	}

	return *o.ValueAmount.Get()
}

// GetValueAmountOk returns a tuple with the ValueAmount field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetEvent200ResponseLineageChildrenInner) GetValueAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ValueAmount.Get(), o.ValueAmount.IsSet()
}

// SetValueAmount sets field value
func (o *GetEvent200ResponseLineageChildrenInner) SetValueAmount(v int32) {
	o.ValueAmount.Set(&v)
}

// GetValueCurrency returns the ValueCurrency field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetEvent200ResponseLineageChildrenInner) GetValueCurrency() string {
	if o == nil || o.ValueCurrency.Get() == nil {
		var ret string
		return ret
	}

	return *o.ValueCurrency.Get()
}

// GetValueCurrencyOk returns a tuple with the ValueCurrency field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetEvent200ResponseLineageChildrenInner) GetValueCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ValueCurrency.Get(), o.ValueCurrency.IsSet()
}

// SetValueCurrency sets field value
func (o *GetEvent200ResponseLineageChildrenInner) SetValueCurrency(v string) {
	o.ValueCurrency.Set(&v)
}

// GetCreatedAt returns the CreatedAt field value
func (o *GetEvent200ResponseLineageChildrenInner) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GetEvent200ResponseLineageChildrenInner) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GetEvent200ResponseLineageChildrenInner) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetConsentBasis returns the ConsentBasis field value
func (o *GetEvent200ResponseLineageChildrenInner) GetConsentBasis() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConsentBasis
}

// GetConsentBasisOk returns a tuple with the ConsentBasis field value
// and a boolean to check if the value has been set.
func (o *GetEvent200ResponseLineageChildrenInner) GetConsentBasisOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConsentBasis, true
}

// SetConsentBasis sets field value
func (o *GetEvent200ResponseLineageChildrenInner) SetConsentBasis(v string) {
	o.ConsentBasis = v
}

// GetMeasurementClass returns the MeasurementClass field value
func (o *GetEvent200ResponseLineageChildrenInner) GetMeasurementClass() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MeasurementClass
}

// GetMeasurementClassOk returns a tuple with the MeasurementClass field value
// and a boolean to check if the value has been set.
func (o *GetEvent200ResponseLineageChildrenInner) GetMeasurementClassOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MeasurementClass, true
}

// SetMeasurementClass sets field value
func (o *GetEvent200ResponseLineageChildrenInner) SetMeasurementClass(v string) {
	o.MeasurementClass = v
}

// GetAttributionJoin returns the AttributionJoin field value
func (o *GetEvent200ResponseLineageChildrenInner) GetAttributionJoin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AttributionJoin
}

// GetAttributionJoinOk returns a tuple with the AttributionJoin field value
// and a boolean to check if the value has been set.
func (o *GetEvent200ResponseLineageChildrenInner) GetAttributionJoinOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttributionJoin, true
}

// SetAttributionJoin sets field value
func (o *GetEvent200ResponseLineageChildrenInner) SetAttributionJoin(v string) {
	o.AttributionJoin = v
}

// GetEnforcementScope returns the EnforcementScope field value
func (o *GetEvent200ResponseLineageChildrenInner) GetEnforcementScope() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EnforcementScope
}

// GetEnforcementScopeOk returns a tuple with the EnforcementScope field value
// and a boolean to check if the value has been set.
func (o *GetEvent200ResponseLineageChildrenInner) GetEnforcementScopeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnforcementScope, true
}

// SetEnforcementScope sets field value
func (o *GetEvent200ResponseLineageChildrenInner) SetEnforcementScope(v string) {
	o.EnforcementScope = v
}

// GetConsentNormalizationVersion returns the ConsentNormalizationVersion field value
func (o *GetEvent200ResponseLineageChildrenInner) GetConsentNormalizationVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConsentNormalizationVersion
}

// GetConsentNormalizationVersionOk returns a tuple with the ConsentNormalizationVersion field value
// and a boolean to check if the value has been set.
func (o *GetEvent200ResponseLineageChildrenInner) GetConsentNormalizationVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConsentNormalizationVersion, true
}

// SetConsentNormalizationVersion sets field value
func (o *GetEvent200ResponseLineageChildrenInner) SetConsentNormalizationVersion(v string) {
	o.ConsentNormalizationVersion = v
}

// GetConsent returns the Consent field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *GetEvent200ResponseLineageChildrenInner) GetConsent() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Consent
}

// GetConsentOk returns a tuple with the Consent field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetEvent200ResponseLineageChildrenInner) GetConsentOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Consent) {
		return nil, false
	}
	return &o.Consent, true
}

// SetConsent sets field value
func (o *GetEvent200ResponseLineageChildrenInner) SetConsent(v interface{}) {
	o.Consent = v
}

// GetUserDataHashed returns the UserDataHashed field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *GetEvent200ResponseLineageChildrenInner) GetUserDataHashed() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.UserDataHashed
}

// GetUserDataHashedOk returns a tuple with the UserDataHashed field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetEvent200ResponseLineageChildrenInner) GetUserDataHashedOk() (*interface{}, bool) {
	if o == nil || IsNil(o.UserDataHashed) {
		return nil, false
	}
	return &o.UserDataHashed, true
}

// SetUserDataHashed sets field value
func (o *GetEvent200ResponseLineageChildrenInner) SetUserDataHashed(v interface{}) {
	o.UserDataHashed = v
}

// GetClickIds returns the ClickIds field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *GetEvent200ResponseLineageChildrenInner) GetClickIds() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.ClickIds
}

// GetClickIdsOk returns a tuple with the ClickIds field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetEvent200ResponseLineageChildrenInner) GetClickIdsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ClickIds) {
		return nil, false
	}
	return &o.ClickIds, true
}

// SetClickIds sets field value
func (o *GetEvent200ResponseLineageChildrenInner) SetClickIds(v interface{}) {
	o.ClickIds = v
}

// GetSession returns the Session field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *GetEvent200ResponseLineageChildrenInner) GetSession() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Session
}

// GetSessionOk returns a tuple with the Session field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetEvent200ResponseLineageChildrenInner) GetSessionOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Session) {
		return nil, false
	}
	return &o.Session, true
}

// SetSession sets field value
func (o *GetEvent200ResponseLineageChildrenInner) SetSession(v interface{}) {
	o.Session = v
}

// GetValueData returns the ValueData field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *GetEvent200ResponseLineageChildrenInner) GetValueData() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.ValueData
}

// GetValueDataOk returns a tuple with the ValueData field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetEvent200ResponseLineageChildrenInner) GetValueDataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ValueData) {
		return nil, false
	}
	return &o.ValueData, true
}

// SetValueData sets field value
func (o *GetEvent200ResponseLineageChildrenInner) SetValueData(v interface{}) {
	o.ValueData = v
}

// GetEventSource returns the EventSource field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetEvent200ResponseLineageChildrenInner) GetEventSource() string {
	if o == nil || o.EventSource.Get() == nil {
		var ret string
		return ret
	}

	return *o.EventSource.Get()
}

// GetEventSourceOk returns a tuple with the EventSource field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetEvent200ResponseLineageChildrenInner) GetEventSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EventSource.Get(), o.EventSource.IsSet()
}

// SetEventSource sets field value
func (o *GetEvent200ResponseLineageChildrenInner) SetEventSource(v string) {
	o.EventSource.Set(&v)
}

// GetPayloadExpired returns the PayloadExpired field value
func (o *GetEvent200ResponseLineageChildrenInner) GetPayloadExpired() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.PayloadExpired
}

// GetPayloadExpiredOk returns a tuple with the PayloadExpired field value
// and a boolean to check if the value has been set.
func (o *GetEvent200ResponseLineageChildrenInner) GetPayloadExpiredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PayloadExpired, true
}

// SetPayloadExpired sets field value
func (o *GetEvent200ResponseLineageChildrenInner) SetPayloadExpired(v bool) {
	o.PayloadExpired = v
}

func (o GetEvent200ResponseLineageChildrenInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEvent200ResponseLineageChildrenInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["signal_tracker_id"] = o.SignalTrackerId
	toSerialize["parent_event_id"] = o.ParentEventId.Get()
	toSerialize["event_name"] = o.EventName
	toSerialize["event_time"] = o.EventTime
	toSerialize["action_source"] = o.ActionSource
	toSerialize["event_class"] = o.EventClass
	toSerialize["order_id"] = o.OrderId.Get()
	toSerialize["value_amount"] = o.ValueAmount.Get()
	toSerialize["value_currency"] = o.ValueCurrency.Get()
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["consent_basis"] = o.ConsentBasis
	toSerialize["measurement_class"] = o.MeasurementClass
	toSerialize["attribution_join"] = o.AttributionJoin
	toSerialize["enforcement_scope"] = o.EnforcementScope
	toSerialize["consent_normalization_version"] = o.ConsentNormalizationVersion
	if o.Consent != nil {
		toSerialize["consent"] = o.Consent
	}
	if o.UserDataHashed != nil {
		toSerialize["user_data_hashed"] = o.UserDataHashed
	}
	if o.ClickIds != nil {
		toSerialize["click_ids"] = o.ClickIds
	}
	if o.Session != nil {
		toSerialize["session"] = o.Session
	}
	if o.ValueData != nil {
		toSerialize["value_data"] = o.ValueData
	}
	toSerialize["event_source"] = o.EventSource.Get()
	toSerialize["payload_expired"] = o.PayloadExpired

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetEvent200ResponseLineageChildrenInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"signal_tracker_id",
		"parent_event_id",
		"event_name",
		"event_time",
		"action_source",
		"event_class",
		"order_id",
		"value_amount",
		"value_currency",
		"created_at",
		"consent_basis",
		"measurement_class",
		"attribution_join",
		"enforcement_scope",
		"consent_normalization_version",
		"consent",
		"user_data_hashed",
		"click_ids",
		"session",
		"value_data",
		"event_source",
		"payload_expired",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetEvent200ResponseLineageChildrenInner := _GetEvent200ResponseLineageChildrenInner{}

	err = json.Unmarshal(data, &varGetEvent200ResponseLineageChildrenInner)

	if err != nil {
		return err
	}

	*o = GetEvent200ResponseLineageChildrenInner(varGetEvent200ResponseLineageChildrenInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "signal_tracker_id")
		delete(additionalProperties, "parent_event_id")
		delete(additionalProperties, "event_name")
		delete(additionalProperties, "event_time")
		delete(additionalProperties, "action_source")
		delete(additionalProperties, "event_class")
		delete(additionalProperties, "order_id")
		delete(additionalProperties, "value_amount")
		delete(additionalProperties, "value_currency")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "consent_basis")
		delete(additionalProperties, "measurement_class")
		delete(additionalProperties, "attribution_join")
		delete(additionalProperties, "enforcement_scope")
		delete(additionalProperties, "consent_normalization_version")
		delete(additionalProperties, "consent")
		delete(additionalProperties, "user_data_hashed")
		delete(additionalProperties, "click_ids")
		delete(additionalProperties, "session")
		delete(additionalProperties, "value_data")
		delete(additionalProperties, "event_source")
		delete(additionalProperties, "payload_expired")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetEvent200ResponseLineageChildrenInner struct {
	value *GetEvent200ResponseLineageChildrenInner
	isSet bool
}

func (v NullableGetEvent200ResponseLineageChildrenInner) Get() *GetEvent200ResponseLineageChildrenInner {
	return v.value
}

func (v *NullableGetEvent200ResponseLineageChildrenInner) Set(val *GetEvent200ResponseLineageChildrenInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEvent200ResponseLineageChildrenInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEvent200ResponseLineageChildrenInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEvent200ResponseLineageChildrenInner(val *GetEvent200ResponseLineageChildrenInner) *NullableGetEvent200ResponseLineageChildrenInner {
	return &NullableGetEvent200ResponseLineageChildrenInner{value: val, isSet: true}
}

func (v NullableGetEvent200ResponseLineageChildrenInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEvent200ResponseLineageChildrenInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
