/*
PlainRouter Conversion API

PlainRouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plainrouter

import (
	"encoding/json"
	"fmt"
)

// checks if the GetReconciliationReport200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetReconciliationReport200Response{}

// GetReconciliationReport200Response struct for GetReconciliationReport200Response
type GetReconciliationReport200Response struct {
	Date                 string                                           `json:"date"`
	Reports              []GetReconciliationReport200ResponseReportsInner `json:"reports"`
	AdditionalProperties map[string]interface{}
}

type _GetReconciliationReport200Response GetReconciliationReport200Response

// NewGetReconciliationReport200Response instantiates a new GetReconciliationReport200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetReconciliationReport200Response(date string, reports []GetReconciliationReport200ResponseReportsInner) *GetReconciliationReport200Response {
	this := GetReconciliationReport200Response{}
	this.Date = date
	this.Reports = reports
	return &this
}

// NewGetReconciliationReport200ResponseWithDefaults instantiates a new GetReconciliationReport200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetReconciliationReport200ResponseWithDefaults() *GetReconciliationReport200Response {
	this := GetReconciliationReport200Response{}
	return &this
}

// GetDate returns the Date field value
func (o *GetReconciliationReport200Response) GetDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *GetReconciliationReport200Response) GetDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *GetReconciliationReport200Response) SetDate(v string) {
	o.Date = v
}

// GetReports returns the Reports field value
func (o *GetReconciliationReport200Response) GetReports() []GetReconciliationReport200ResponseReportsInner {
	if o == nil {
		var ret []GetReconciliationReport200ResponseReportsInner
		return ret
	}

	return o.Reports
}

// GetReportsOk returns a tuple with the Reports field value
// and a boolean to check if the value has been set.
func (o *GetReconciliationReport200Response) GetReportsOk() ([]GetReconciliationReport200ResponseReportsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reports, true
}

// SetReports sets field value
func (o *GetReconciliationReport200Response) SetReports(v []GetReconciliationReport200ResponseReportsInner) {
	o.Reports = v
}

func (o GetReconciliationReport200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetReconciliationReport200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["date"] = o.Date
	toSerialize["reports"] = o.Reports

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetReconciliationReport200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"date",
		"reports",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetReconciliationReport200Response := _GetReconciliationReport200Response{}

	err = json.Unmarshal(data, &varGetReconciliationReport200Response)

	if err != nil {
		return err
	}

	*o = GetReconciliationReport200Response(varGetReconciliationReport200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "date")
		delete(additionalProperties, "reports")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetReconciliationReport200Response struct {
	value *GetReconciliationReport200Response
	isSet bool
}

func (v NullableGetReconciliationReport200Response) Get() *GetReconciliationReport200Response {
	return v.value
}

func (v *NullableGetReconciliationReport200Response) Set(val *GetReconciliationReport200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetReconciliationReport200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetReconciliationReport200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetReconciliationReport200Response(val *GetReconciliationReport200Response) *NullableGetReconciliationReport200Response {
	return &NullableGetReconciliationReport200Response{value: val, isSet: true}
}

func (v NullableGetReconciliationReport200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetReconciliationReport200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
