/*
PlainRouter Conversion API

PlainRouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plainrouter

import (
	"encoding/json"
	"fmt"
)

// checks if the GetSandbox200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSandbox200Response{}

// GetSandbox200Response struct for GetSandbox200Response
type GetSandbox200Response struct {
	Environment            string                            `json:"environment"`
	AuthenticationRequired bool                              `json:"authentication_required"`
	AccountRequired        bool                              `json:"account_required"`
	ProductionData         bool                              `json:"production_data"`
	PersistsData           bool                              `json:"persists_data"`
	ProviderDelivery       bool                              `json:"provider_delivery"`
	Description            string                            `json:"description"`
	SelfServeKey           GetSandbox200ResponseSelfServeKey `json:"self_serve_key"`
	Try                    GetSandbox200ResponseTry          `json:"try"`
	AdditionalProperties   map[string]interface{}
}

type _GetSandbox200Response GetSandbox200Response

// NewGetSandbox200Response instantiates a new GetSandbox200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSandbox200Response(environment string, authenticationRequired bool, accountRequired bool, productionData bool, persistsData bool, providerDelivery bool, description string, selfServeKey GetSandbox200ResponseSelfServeKey, try GetSandbox200ResponseTry) *GetSandbox200Response {
	this := GetSandbox200Response{}
	this.Environment = environment
	this.AuthenticationRequired = authenticationRequired
	this.AccountRequired = accountRequired
	this.ProductionData = productionData
	this.PersistsData = persistsData
	this.ProviderDelivery = providerDelivery
	this.Description = description
	this.SelfServeKey = selfServeKey
	this.Try = try
	return &this
}

// NewGetSandbox200ResponseWithDefaults instantiates a new GetSandbox200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSandbox200ResponseWithDefaults() *GetSandbox200Response {
	this := GetSandbox200Response{}
	return &this
}

// GetEnvironment returns the Environment field value
func (o *GetSandbox200Response) GetEnvironment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value
// and a boolean to check if the value has been set.
func (o *GetSandbox200Response) GetEnvironmentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Environment, true
}

// SetEnvironment sets field value
func (o *GetSandbox200Response) SetEnvironment(v string) {
	o.Environment = v
}

// GetAuthenticationRequired returns the AuthenticationRequired field value
func (o *GetSandbox200Response) GetAuthenticationRequired() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AuthenticationRequired
}

// GetAuthenticationRequiredOk returns a tuple with the AuthenticationRequired field value
// and a boolean to check if the value has been set.
func (o *GetSandbox200Response) GetAuthenticationRequiredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthenticationRequired, true
}

// SetAuthenticationRequired sets field value
func (o *GetSandbox200Response) SetAuthenticationRequired(v bool) {
	o.AuthenticationRequired = v
}

// GetAccountRequired returns the AccountRequired field value
func (o *GetSandbox200Response) GetAccountRequired() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AccountRequired
}

// GetAccountRequiredOk returns a tuple with the AccountRequired field value
// and a boolean to check if the value has been set.
func (o *GetSandbox200Response) GetAccountRequiredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountRequired, true
}

// SetAccountRequired sets field value
func (o *GetSandbox200Response) SetAccountRequired(v bool) {
	o.AccountRequired = v
}

// GetProductionData returns the ProductionData field value
func (o *GetSandbox200Response) GetProductionData() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ProductionData
}

// GetProductionDataOk returns a tuple with the ProductionData field value
// and a boolean to check if the value has been set.
func (o *GetSandbox200Response) GetProductionDataOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProductionData, true
}

// SetProductionData sets field value
func (o *GetSandbox200Response) SetProductionData(v bool) {
	o.ProductionData = v
}

// GetPersistsData returns the PersistsData field value
func (o *GetSandbox200Response) GetPersistsData() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.PersistsData
}

// GetPersistsDataOk returns a tuple with the PersistsData field value
// and a boolean to check if the value has been set.
func (o *GetSandbox200Response) GetPersistsDataOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PersistsData, true
}

// SetPersistsData sets field value
func (o *GetSandbox200Response) SetPersistsData(v bool) {
	o.PersistsData = v
}

// GetProviderDelivery returns the ProviderDelivery field value
func (o *GetSandbox200Response) GetProviderDelivery() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ProviderDelivery
}

// GetProviderDeliveryOk returns a tuple with the ProviderDelivery field value
// and a boolean to check if the value has been set.
func (o *GetSandbox200Response) GetProviderDeliveryOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderDelivery, true
}

// SetProviderDelivery sets field value
func (o *GetSandbox200Response) SetProviderDelivery(v bool) {
	o.ProviderDelivery = v
}

// GetDescription returns the Description field value
func (o *GetSandbox200Response) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *GetSandbox200Response) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *GetSandbox200Response) SetDescription(v string) {
	o.Description = v
}

// GetSelfServeKey returns the SelfServeKey field value
func (o *GetSandbox200Response) GetSelfServeKey() GetSandbox200ResponseSelfServeKey {
	if o == nil {
		var ret GetSandbox200ResponseSelfServeKey
		return ret
	}

	return o.SelfServeKey
}

// GetSelfServeKeyOk returns a tuple with the SelfServeKey field value
// and a boolean to check if the value has been set.
func (o *GetSandbox200Response) GetSelfServeKeyOk() (*GetSandbox200ResponseSelfServeKey, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SelfServeKey, true
}

// SetSelfServeKey sets field value
func (o *GetSandbox200Response) SetSelfServeKey(v GetSandbox200ResponseSelfServeKey) {
	o.SelfServeKey = v
}

// GetTry returns the Try field value
func (o *GetSandbox200Response) GetTry() GetSandbox200ResponseTry {
	if o == nil {
		var ret GetSandbox200ResponseTry
		return ret
	}

	return o.Try
}

// GetTryOk returns a tuple with the Try field value
// and a boolean to check if the value has been set.
func (o *GetSandbox200Response) GetTryOk() (*GetSandbox200ResponseTry, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Try, true
}

// SetTry sets field value
func (o *GetSandbox200Response) SetTry(v GetSandbox200ResponseTry) {
	o.Try = v
}

func (o GetSandbox200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSandbox200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["environment"] = o.Environment
	toSerialize["authentication_required"] = o.AuthenticationRequired
	toSerialize["account_required"] = o.AccountRequired
	toSerialize["production_data"] = o.ProductionData
	toSerialize["persists_data"] = o.PersistsData
	toSerialize["provider_delivery"] = o.ProviderDelivery
	toSerialize["description"] = o.Description
	toSerialize["self_serve_key"] = o.SelfServeKey
	toSerialize["try"] = o.Try

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetSandbox200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"environment",
		"authentication_required",
		"account_required",
		"production_data",
		"persists_data",
		"provider_delivery",
		"description",
		"self_serve_key",
		"try",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetSandbox200Response := _GetSandbox200Response{}

	err = json.Unmarshal(data, &varGetSandbox200Response)

	if err != nil {
		return err
	}

	*o = GetSandbox200Response(varGetSandbox200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "environment")
		delete(additionalProperties, "authentication_required")
		delete(additionalProperties, "account_required")
		delete(additionalProperties, "production_data")
		delete(additionalProperties, "persists_data")
		delete(additionalProperties, "provider_delivery")
		delete(additionalProperties, "description")
		delete(additionalProperties, "self_serve_key")
		delete(additionalProperties, "try")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetSandbox200Response struct {
	value *GetSandbox200Response
	isSet bool
}

func (v NullableGetSandbox200Response) Get() *GetSandbox200Response {
	return v.value
}

func (v *NullableGetSandbox200Response) Set(val *GetSandbox200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSandbox200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSandbox200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSandbox200Response(val *GetSandbox200Response) *NullableGetSandbox200Response {
	return &NullableGetSandbox200Response{value: val, isSet: true}
}

func (v NullableGetSandbox200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSandbox200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
