/*
PlainRouter Conversion API

PlainRouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plainrouter

import (
	"encoding/json"
	"fmt"
)

// checks if the SetDestinationTestMode200ResponseDestination type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetDestinationTestMode200ResponseDestination{}

// SetDestinationTestMode200ResponseDestination struct for SetDestinationTestMode200ResponseDestination
type SetDestinationTestMode200ResponseDestination struct {
	Id                   string                      `json:"id"`
	SignalTrackerId      string                      `json:"signal_tracker_id"`
	PlatformAdAccountId  NullableInt32               `json:"platform_ad_account_id"`
	Type                 DestinationType             `json:"type"`
	CredentialSource     DestinationCredentialSource `json:"credential_source"`
	Config               interface{}                 `json:"config"`
	Status               DestinationStatus           `json:"status"`
	CreatedAt            NullableString              `json:"created_at"`
	UpdatedAt            NullableString              `json:"updated_at"`
	AdditionalProperties map[string]interface{}
}

type _SetDestinationTestMode200ResponseDestination SetDestinationTestMode200ResponseDestination

// NewSetDestinationTestMode200ResponseDestination instantiates a new SetDestinationTestMode200ResponseDestination object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetDestinationTestMode200ResponseDestination(id string, signalTrackerId string, platformAdAccountId NullableInt32, type_ DestinationType, credentialSource DestinationCredentialSource, config interface{}, status DestinationStatus, createdAt NullableString, updatedAt NullableString) *SetDestinationTestMode200ResponseDestination {
	this := SetDestinationTestMode200ResponseDestination{}
	this.Id = id
	this.SignalTrackerId = signalTrackerId
	this.PlatformAdAccountId = platformAdAccountId
	this.Type = type_
	this.CredentialSource = credentialSource
	this.Config = config
	this.Status = status
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewSetDestinationTestMode200ResponseDestinationWithDefaults instantiates a new SetDestinationTestMode200ResponseDestination object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetDestinationTestMode200ResponseDestinationWithDefaults() *SetDestinationTestMode200ResponseDestination {
	this := SetDestinationTestMode200ResponseDestination{}
	return &this
}

// GetId returns the Id field value
func (o *SetDestinationTestMode200ResponseDestination) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SetDestinationTestMode200ResponseDestination) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SetDestinationTestMode200ResponseDestination) SetId(v string) {
	o.Id = v
}

// GetSignalTrackerId returns the SignalTrackerId field value
func (o *SetDestinationTestMode200ResponseDestination) GetSignalTrackerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SignalTrackerId
}

// GetSignalTrackerIdOk returns a tuple with the SignalTrackerId field value
// and a boolean to check if the value has been set.
func (o *SetDestinationTestMode200ResponseDestination) GetSignalTrackerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SignalTrackerId, true
}

// SetSignalTrackerId sets field value
func (o *SetDestinationTestMode200ResponseDestination) SetSignalTrackerId(v string) {
	o.SignalTrackerId = v
}

// GetPlatformAdAccountId returns the PlatformAdAccountId field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *SetDestinationTestMode200ResponseDestination) GetPlatformAdAccountId() int32 {
	if o == nil || o.PlatformAdAccountId.Get() == nil {
		var ret int32
		return ret
	}

	return *o.PlatformAdAccountId.Get()
}

// GetPlatformAdAccountIdOk returns a tuple with the PlatformAdAccountId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SetDestinationTestMode200ResponseDestination) GetPlatformAdAccountIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PlatformAdAccountId.Get(), o.PlatformAdAccountId.IsSet()
}

// SetPlatformAdAccountId sets field value
func (o *SetDestinationTestMode200ResponseDestination) SetPlatformAdAccountId(v int32) {
	o.PlatformAdAccountId.Set(&v)
}

// GetType returns the Type field value
func (o *SetDestinationTestMode200ResponseDestination) GetType() DestinationType {
	if o == nil {
		var ret DestinationType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SetDestinationTestMode200ResponseDestination) GetTypeOk() (*DestinationType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SetDestinationTestMode200ResponseDestination) SetType(v DestinationType) {
	o.Type = v
}

// GetCredentialSource returns the CredentialSource field value
func (o *SetDestinationTestMode200ResponseDestination) GetCredentialSource() DestinationCredentialSource {
	if o == nil {
		var ret DestinationCredentialSource
		return ret
	}

	return o.CredentialSource
}

// GetCredentialSourceOk returns a tuple with the CredentialSource field value
// and a boolean to check if the value has been set.
func (o *SetDestinationTestMode200ResponseDestination) GetCredentialSourceOk() (*DestinationCredentialSource, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CredentialSource, true
}

// SetCredentialSource sets field value
func (o *SetDestinationTestMode200ResponseDestination) SetCredentialSource(v DestinationCredentialSource) {
	o.CredentialSource = v
}

// GetConfig returns the Config field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *SetDestinationTestMode200ResponseDestination) GetConfig() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Config
}

// GetConfigOk returns a tuple with the Config field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SetDestinationTestMode200ResponseDestination) GetConfigOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Config) {
		return nil, false
	}
	return &o.Config, true
}

// SetConfig sets field value
func (o *SetDestinationTestMode200ResponseDestination) SetConfig(v interface{}) {
	o.Config = v
}

// GetStatus returns the Status field value
func (o *SetDestinationTestMode200ResponseDestination) GetStatus() DestinationStatus {
	if o == nil {
		var ret DestinationStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SetDestinationTestMode200ResponseDestination) GetStatusOk() (*DestinationStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SetDestinationTestMode200ResponseDestination) SetStatus(v DestinationStatus) {
	o.Status = v
}

// GetCreatedAt returns the CreatedAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SetDestinationTestMode200ResponseDestination) GetCreatedAt() string {
	if o == nil || o.CreatedAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SetDestinationTestMode200ResponseDestination) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// SetCreatedAt sets field value
func (o *SetDestinationTestMode200ResponseDestination) SetCreatedAt(v string) {
	o.CreatedAt.Set(&v)
}

// GetUpdatedAt returns the UpdatedAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SetDestinationTestMode200ResponseDestination) GetUpdatedAt() string {
	if o == nil || o.UpdatedAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SetDestinationTestMode200ResponseDestination) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// SetUpdatedAt sets field value
func (o *SetDestinationTestMode200ResponseDestination) SetUpdatedAt(v string) {
	o.UpdatedAt.Set(&v)
}

func (o SetDestinationTestMode200ResponseDestination) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetDestinationTestMode200ResponseDestination) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["signal_tracker_id"] = o.SignalTrackerId
	toSerialize["platform_ad_account_id"] = o.PlatformAdAccountId.Get()
	toSerialize["type"] = o.Type
	toSerialize["credential_source"] = o.CredentialSource
	if o.Config != nil {
		toSerialize["config"] = o.Config
	}
	toSerialize["status"] = o.Status
	toSerialize["created_at"] = o.CreatedAt.Get()
	toSerialize["updated_at"] = o.UpdatedAt.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SetDestinationTestMode200ResponseDestination) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"signal_tracker_id",
		"platform_ad_account_id",
		"type",
		"credential_source",
		"config",
		"status",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetDestinationTestMode200ResponseDestination := _SetDestinationTestMode200ResponseDestination{}

	err = json.Unmarshal(data, &varSetDestinationTestMode200ResponseDestination)

	if err != nil {
		return err
	}

	*o = SetDestinationTestMode200ResponseDestination(varSetDestinationTestMode200ResponseDestination)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "signal_tracker_id")
		delete(additionalProperties, "platform_ad_account_id")
		delete(additionalProperties, "type")
		delete(additionalProperties, "credential_source")
		delete(additionalProperties, "config")
		delete(additionalProperties, "status")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSetDestinationTestMode200ResponseDestination struct {
	value *SetDestinationTestMode200ResponseDestination
	isSet bool
}

func (v NullableSetDestinationTestMode200ResponseDestination) Get() *SetDestinationTestMode200ResponseDestination {
	return v.value
}

func (v *NullableSetDestinationTestMode200ResponseDestination) Set(val *SetDestinationTestMode200ResponseDestination) {
	v.value = val
	v.isSet = true
}

func (v NullableSetDestinationTestMode200ResponseDestination) IsSet() bool {
	return v.isSet
}

func (v *NullableSetDestinationTestMode200ResponseDestination) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetDestinationTestMode200ResponseDestination(val *SetDestinationTestMode200ResponseDestination) *NullableSetDestinationTestMode200ResponseDestination {
	return &NullableSetDestinationTestMode200ResponseDestination{value: val, isSet: true}
}

func (v NullableSetDestinationTestMode200ResponseDestination) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetDestinationTestMode200ResponseDestination) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
