/*
PlainRouter Conversion API

PlainRouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plainrouter

import (
	"encoding/json"
	"fmt"
)

// JurisdictionPolicyClass The two policy classes used by the single Signals collector. The enum intentionally has no country or region members. Country evidence is an edge input used to derive a policy class and is never a ledger value.
type JurisdictionPolicyClass string

// List of JurisdictionPolicyClass
const (
	JURISDICTIONPOLICYCLASS_STRICT_EU                JurisdictionPolicyClass = "strict_eu"
	JURISDICTIONPOLICYCLASS_GLOBAL                   JurisdictionPolicyClass = "global"
	JURISDICTIONPOLICYCLASS_UNKNOWN_DEFAULT_OPEN_API JurisdictionPolicyClass = "unknown_default_open_api"
)

// All allowed values of JurisdictionPolicyClass enum
var AllowedJurisdictionPolicyClassEnumValues = []JurisdictionPolicyClass{
	"strict_eu",
	"global",
	"unknown_default_open_api",
}

func (v *JurisdictionPolicyClass) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := JurisdictionPolicyClass(value)
	for _, existing := range AllowedJurisdictionPolicyClassEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = JURISDICTIONPOLICYCLASS_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewJurisdictionPolicyClassFromValue returns a pointer to a valid JurisdictionPolicyClass
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewJurisdictionPolicyClassFromValue(v string) (*JurisdictionPolicyClass, error) {
	ev := JurisdictionPolicyClass(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for JurisdictionPolicyClass: valid values are %v", v, AllowedJurisdictionPolicyClassEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v JurisdictionPolicyClass) IsValid() bool {
	for _, existing := range AllowedJurisdictionPolicyClassEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to JurisdictionPolicyClass value
func (v JurisdictionPolicyClass) Ptr() *JurisdictionPolicyClass {
	return &v
}

type NullableJurisdictionPolicyClass struct {
	value *JurisdictionPolicyClass
	isSet bool
}

func (v NullableJurisdictionPolicyClass) Get() *JurisdictionPolicyClass {
	return v.value
}

func (v *NullableJurisdictionPolicyClass) Set(val *JurisdictionPolicyClass) {
	v.value = val
	v.isSet = true
}

func (v NullableJurisdictionPolicyClass) IsSet() bool {
	return v.isSet
}

func (v *NullableJurisdictionPolicyClass) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJurisdictionPolicyClass(val *JurisdictionPolicyClass) *NullableJurisdictionPolicyClass {
	return &NullableJurisdictionPolicyClass{value: val, isSet: true}
}

func (v NullableJurisdictionPolicyClass) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJurisdictionPolicyClass) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
