/*
PlainRouter Conversion API

PlainRouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plainrouter

import (
	"encoding/json"
	"fmt"
)

// TrafficClass The only persisted traffic verdicts for passive document arrivals. Request facts and classifier reasons never cross the stripping boundary.
type TrafficClass string

// List of TrafficClass
const (
	TRAFFICCLASS_VALID                    TrafficClass = "valid"
	TRAFFICCLASS_INVALID                  TrafficClass = "invalid"
	TRAFFICCLASS_UNKNOWN_DEFAULT_OPEN_API TrafficClass = "unknown_default_open_api"
)

// All allowed values of TrafficClass enum
var AllowedTrafficClassEnumValues = []TrafficClass{
	"valid",
	"invalid",
	"unknown_default_open_api",
}

func (v *TrafficClass) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TrafficClass(value)
	for _, existing := range AllowedTrafficClassEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = TRAFFICCLASS_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewTrafficClassFromValue returns a pointer to a valid TrafficClass
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTrafficClassFromValue(v string) (*TrafficClass, error) {
	ev := TrafficClass(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TrafficClass: valid values are %v", v, AllowedTrafficClassEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TrafficClass) IsValid() bool {
	for _, existing := range AllowedTrafficClassEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TrafficClass value
func (v TrafficClass) Ptr() *TrafficClass {
	return &v
}

type NullableTrafficClass struct {
	value *TrafficClass
	isSet bool
}

func (v NullableTrafficClass) Get() *TrafficClass {
	return v.value
}

func (v *NullableTrafficClass) Set(val *TrafficClass) {
	v.value = val
	v.isSet = true
}

func (v NullableTrafficClass) IsSet() bool {
	return v.isSet
}

func (v *NullableTrafficClass) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrafficClass(val *TrafficClass) *NullableTrafficClass {
	return &NullableTrafficClass{value: val, isSet: true}
}

func (v NullableTrafficClass) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrafficClass) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
