/*
PlainRouter Conversion API

PlainRouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plainrouter

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the EmqSnapshot type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmqSnapshot{}

// EmqSnapshot struct for EmqSnapshot
type EmqSnapshot struct {
	Id                   int32           `json:"id"`
	SignalTrackerId      string          `json:"signal_tracker_id"`
	DestinationId        string          `json:"destination_id"`
	Score                float32         `json:"score"`
	WeekOverWeekChange   NullableFloat32 `json:"week_over_week_change"`
	Alerted              bool            `json:"alerted"`
	PlatformResponse     []interface{}   `json:"platform_response"`
	MeasuredAt           time.Time       `json:"measured_at"`
	CreatedAt            NullableTime    `json:"created_at"`
	UpdatedAt            NullableTime    `json:"updated_at"`
	AdditionalProperties map[string]interface{}
}

type _EmqSnapshot EmqSnapshot

// NewEmqSnapshot instantiates a new EmqSnapshot object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmqSnapshot(id int32, signalTrackerId string, destinationId string, score float32, weekOverWeekChange NullableFloat32, alerted bool, platformResponse []interface{}, measuredAt time.Time, createdAt NullableTime, updatedAt NullableTime) *EmqSnapshot {
	this := EmqSnapshot{}
	this.Id = id
	this.SignalTrackerId = signalTrackerId
	this.DestinationId = destinationId
	this.Score = score
	this.WeekOverWeekChange = weekOverWeekChange
	this.Alerted = alerted
	this.PlatformResponse = platformResponse
	this.MeasuredAt = measuredAt
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewEmqSnapshotWithDefaults instantiates a new EmqSnapshot object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmqSnapshotWithDefaults() *EmqSnapshot {
	this := EmqSnapshot{}
	return &this
}

// GetId returns the Id field value
func (o *EmqSnapshot) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *EmqSnapshot) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *EmqSnapshot) SetId(v int32) {
	o.Id = v
}

// GetSignalTrackerId returns the SignalTrackerId field value
func (o *EmqSnapshot) GetSignalTrackerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SignalTrackerId
}

// GetSignalTrackerIdOk returns a tuple with the SignalTrackerId field value
// and a boolean to check if the value has been set.
func (o *EmqSnapshot) GetSignalTrackerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SignalTrackerId, true
}

// SetSignalTrackerId sets field value
func (o *EmqSnapshot) SetSignalTrackerId(v string) {
	o.SignalTrackerId = v
}

// GetDestinationId returns the DestinationId field value
func (o *EmqSnapshot) GetDestinationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DestinationId
}

// GetDestinationIdOk returns a tuple with the DestinationId field value
// and a boolean to check if the value has been set.
func (o *EmqSnapshot) GetDestinationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DestinationId, true
}

// SetDestinationId sets field value
func (o *EmqSnapshot) SetDestinationId(v string) {
	o.DestinationId = v
}

// GetScore returns the Score field value
func (o *EmqSnapshot) GetScore() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Score
}

// GetScoreOk returns a tuple with the Score field value
// and a boolean to check if the value has been set.
func (o *EmqSnapshot) GetScoreOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Score, true
}

// SetScore sets field value
func (o *EmqSnapshot) SetScore(v float32) {
	o.Score = v
}

// GetWeekOverWeekChange returns the WeekOverWeekChange field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *EmqSnapshot) GetWeekOverWeekChange() float32 {
	if o == nil || o.WeekOverWeekChange.Get() == nil {
		var ret float32
		return ret
	}

	return *o.WeekOverWeekChange.Get()
}

// GetWeekOverWeekChangeOk returns a tuple with the WeekOverWeekChange field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmqSnapshot) GetWeekOverWeekChangeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.WeekOverWeekChange.Get(), o.WeekOverWeekChange.IsSet()
}

// SetWeekOverWeekChange sets field value
func (o *EmqSnapshot) SetWeekOverWeekChange(v float32) {
	o.WeekOverWeekChange.Set(&v)
}

// GetAlerted returns the Alerted field value
func (o *EmqSnapshot) GetAlerted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Alerted
}

// GetAlertedOk returns a tuple with the Alerted field value
// and a boolean to check if the value has been set.
func (o *EmqSnapshot) GetAlertedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Alerted, true
}

// SetAlerted sets field value
func (o *EmqSnapshot) SetAlerted(v bool) {
	o.Alerted = v
}

// GetPlatformResponse returns the PlatformResponse field value
// If the value is explicit nil, the zero value for []interface{} will be returned
func (o *EmqSnapshot) GetPlatformResponse() []interface{} {
	if o == nil {
		var ret []interface{}
		return ret
	}

	return o.PlatformResponse
}

// GetPlatformResponseOk returns a tuple with the PlatformResponse field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmqSnapshot) GetPlatformResponseOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.PlatformResponse) {
		return nil, false
	}
	return o.PlatformResponse, true
}

// SetPlatformResponse sets field value
func (o *EmqSnapshot) SetPlatformResponse(v []interface{}) {
	o.PlatformResponse = v
}

// GetMeasuredAt returns the MeasuredAt field value
func (o *EmqSnapshot) GetMeasuredAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.MeasuredAt
}

// GetMeasuredAtOk returns a tuple with the MeasuredAt field value
// and a boolean to check if the value has been set.
func (o *EmqSnapshot) GetMeasuredAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MeasuredAt, true
}

// SetMeasuredAt sets field value
func (o *EmqSnapshot) SetMeasuredAt(v time.Time) {
	o.MeasuredAt = v
}

// GetCreatedAt returns the CreatedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *EmqSnapshot) GetCreatedAt() time.Time {
	if o == nil || o.CreatedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmqSnapshot) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// SetCreatedAt sets field value
func (o *EmqSnapshot) SetCreatedAt(v time.Time) {
	o.CreatedAt.Set(&v)
}

// GetUpdatedAt returns the UpdatedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *EmqSnapshot) GetUpdatedAt() time.Time {
	if o == nil || o.UpdatedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmqSnapshot) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// SetUpdatedAt sets field value
func (o *EmqSnapshot) SetUpdatedAt(v time.Time) {
	o.UpdatedAt.Set(&v)
}

func (o EmqSnapshot) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmqSnapshot) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["signal_tracker_id"] = o.SignalTrackerId
	toSerialize["destination_id"] = o.DestinationId
	toSerialize["score"] = o.Score
	toSerialize["week_over_week_change"] = o.WeekOverWeekChange.Get()
	toSerialize["alerted"] = o.Alerted
	if o.PlatformResponse != nil {
		toSerialize["platform_response"] = o.PlatformResponse
	}
	toSerialize["measured_at"] = o.MeasuredAt
	toSerialize["created_at"] = o.CreatedAt.Get()
	toSerialize["updated_at"] = o.UpdatedAt.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EmqSnapshot) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"signal_tracker_id",
		"destination_id",
		"score",
		"week_over_week_change",
		"alerted",
		"platform_response",
		"measured_at",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmqSnapshot := _EmqSnapshot{}

	err = json.Unmarshal(data, &varEmqSnapshot)

	if err != nil {
		return err
	}

	*o = EmqSnapshot(varEmqSnapshot)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "signal_tracker_id")
		delete(additionalProperties, "destination_id")
		delete(additionalProperties, "score")
		delete(additionalProperties, "week_over_week_change")
		delete(additionalProperties, "alerted")
		delete(additionalProperties, "platform_response")
		delete(additionalProperties, "measured_at")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEmqSnapshot struct {
	value *EmqSnapshot
	isSet bool
}

func (v NullableEmqSnapshot) Get() *EmqSnapshot {
	return v.value
}

func (v *NullableEmqSnapshot) Set(val *EmqSnapshot) {
	v.value = val
	v.isSet = true
}

func (v NullableEmqSnapshot) IsSet() bool {
	return v.isSet
}

func (v *NullableEmqSnapshot) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmqSnapshot(val *EmqSnapshot) *NullableEmqSnapshot {
	return &NullableEmqSnapshot{value: val, isSet: true}
}

func (v NullableEmqSnapshot) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmqSnapshot) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
