/*
PlainRouter Conversion API

PlainRouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plainrouter

import (
	"encoding/json"
	"fmt"
)

// CreateEventRequestAnyOfEventTime Unix timestamp or ISO-8601 date-time. Defaults to receipt time.
type CreateEventRequestAnyOfEventTime struct {
	Int32  *int32
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *CreateEventRequestAnyOfEventTime) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into Int32
	err = json.Unmarshal(data, &dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			return nil // data stored in dst.Int32, return on the first match
		}
	} else {
		dst.Int32 = nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(CreateEventRequestAnyOfEventTime)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CreateEventRequestAnyOfEventTime) MarshalJSON() ([]byte, error) {
	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableCreateEventRequestAnyOfEventTime struct {
	value *CreateEventRequestAnyOfEventTime
	isSet bool
}

func (v NullableCreateEventRequestAnyOfEventTime) Get() *CreateEventRequestAnyOfEventTime {
	return v.value
}

func (v *NullableCreateEventRequestAnyOfEventTime) Set(val *CreateEventRequestAnyOfEventTime) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEventRequestAnyOfEventTime) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEventRequestAnyOfEventTime) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEventRequestAnyOfEventTime(val *CreateEventRequestAnyOfEventTime) *NullableCreateEventRequestAnyOfEventTime {
	return &NullableCreateEventRequestAnyOfEventTime{value: val, isSet: true}
}

func (v NullableCreateEventRequestAnyOfEventTime) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEventRequestAnyOfEventTime) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
