/*
PlainRouter Conversion API

PlainRouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plainrouter

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateSandboxKey201ResponseUse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSandboxKey201ResponseUse{}

// CreateSandboxKey201ResponseUse struct for CreateSandboxKey201ResponseUse
type CreateSandboxKey201ResponseUse struct {
	Method               string `json:"method"`
	Url                  string `json:"url"`
	Authorization        string `json:"authorization"`
	AdditionalProperties map[string]interface{}
}

type _CreateSandboxKey201ResponseUse CreateSandboxKey201ResponseUse

// NewCreateSandboxKey201ResponseUse instantiates a new CreateSandboxKey201ResponseUse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSandboxKey201ResponseUse(method string, url string, authorization string) *CreateSandboxKey201ResponseUse {
	this := CreateSandboxKey201ResponseUse{}
	this.Method = method
	this.Url = url
	this.Authorization = authorization
	return &this
}

// NewCreateSandboxKey201ResponseUseWithDefaults instantiates a new CreateSandboxKey201ResponseUse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSandboxKey201ResponseUseWithDefaults() *CreateSandboxKey201ResponseUse {
	this := CreateSandboxKey201ResponseUse{}
	return &this
}

// GetMethod returns the Method field value
func (o *CreateSandboxKey201ResponseUse) GetMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Method
}

// GetMethodOk returns a tuple with the Method field value
// and a boolean to check if the value has been set.
func (o *CreateSandboxKey201ResponseUse) GetMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Method, true
}

// SetMethod sets field value
func (o *CreateSandboxKey201ResponseUse) SetMethod(v string) {
	o.Method = v
}

// GetUrl returns the Url field value
func (o *CreateSandboxKey201ResponseUse) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *CreateSandboxKey201ResponseUse) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *CreateSandboxKey201ResponseUse) SetUrl(v string) {
	o.Url = v
}

// GetAuthorization returns the Authorization field value
func (o *CreateSandboxKey201ResponseUse) GetAuthorization() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Authorization
}

// GetAuthorizationOk returns a tuple with the Authorization field value
// and a boolean to check if the value has been set.
func (o *CreateSandboxKey201ResponseUse) GetAuthorizationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Authorization, true
}

// SetAuthorization sets field value
func (o *CreateSandboxKey201ResponseUse) SetAuthorization(v string) {
	o.Authorization = v
}

func (o CreateSandboxKey201ResponseUse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSandboxKey201ResponseUse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["method"] = o.Method
	toSerialize["url"] = o.Url
	toSerialize["authorization"] = o.Authorization

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateSandboxKey201ResponseUse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"method",
		"url",
		"authorization",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateSandboxKey201ResponseUse := _CreateSandboxKey201ResponseUse{}

	err = json.Unmarshal(data, &varCreateSandboxKey201ResponseUse)

	if err != nil {
		return err
	}

	*o = CreateSandboxKey201ResponseUse(varCreateSandboxKey201ResponseUse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "method")
		delete(additionalProperties, "url")
		delete(additionalProperties, "authorization")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateSandboxKey201ResponseUse struct {
	value *CreateSandboxKey201ResponseUse
	isSet bool
}

func (v NullableCreateSandboxKey201ResponseUse) Get() *CreateSandboxKey201ResponseUse {
	return v.value
}

func (v *NullableCreateSandboxKey201ResponseUse) Set(val *CreateSandboxKey201ResponseUse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSandboxKey201ResponseUse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSandboxKey201ResponseUse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSandboxKey201ResponseUse(val *CreateSandboxKey201ResponseUse) *NullableCreateSandboxKey201ResponseUse {
	return &NullableCreateSandboxKey201ResponseUse{value: val, isSet: true}
}

func (v NullableCreateSandboxKey201ResponseUse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSandboxKey201ResponseUse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
