/*
PlainRouter Conversion API

PlainRouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plainrouter

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateSandboxKey201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSandboxKey201Response{}

// CreateSandboxKey201Response struct for CreateSandboxKey201Response
type CreateSandboxKey201Response struct {
	ApiKey               string                         `json:"api_key"`
	TokenType            string                         `json:"token_type"`
	ExpiresIn            int32                          `json:"expires_in"`
	ExpiresAt            string                         `json:"expires_at"`
	Scope                string                         `json:"scope"`
	ProductionAccess     bool                           `json:"production_access"`
	Use                  CreateSandboxKey201ResponseUse `json:"use"`
	AdditionalProperties map[string]interface{}
}

type _CreateSandboxKey201Response CreateSandboxKey201Response

// NewCreateSandboxKey201Response instantiates a new CreateSandboxKey201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSandboxKey201Response(apiKey string, tokenType string, expiresIn int32, expiresAt string, scope string, productionAccess bool, use CreateSandboxKey201ResponseUse) *CreateSandboxKey201Response {
	this := CreateSandboxKey201Response{}
	this.ApiKey = apiKey
	this.TokenType = tokenType
	this.ExpiresIn = expiresIn
	this.ExpiresAt = expiresAt
	this.Scope = scope
	this.ProductionAccess = productionAccess
	this.Use = use
	return &this
}

// NewCreateSandboxKey201ResponseWithDefaults instantiates a new CreateSandboxKey201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSandboxKey201ResponseWithDefaults() *CreateSandboxKey201Response {
	this := CreateSandboxKey201Response{}
	return &this
}

// GetApiKey returns the ApiKey field value
func (o *CreateSandboxKey201Response) GetApiKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value
// and a boolean to check if the value has been set.
func (o *CreateSandboxKey201Response) GetApiKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiKey, true
}

// SetApiKey sets field value
func (o *CreateSandboxKey201Response) SetApiKey(v string) {
	o.ApiKey = v
}

// GetTokenType returns the TokenType field value
func (o *CreateSandboxKey201Response) GetTokenType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenType
}

// GetTokenTypeOk returns a tuple with the TokenType field value
// and a boolean to check if the value has been set.
func (o *CreateSandboxKey201Response) GetTokenTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenType, true
}

// SetTokenType sets field value
func (o *CreateSandboxKey201Response) SetTokenType(v string) {
	o.TokenType = v
}

// GetExpiresIn returns the ExpiresIn field value
func (o *CreateSandboxKey201Response) GetExpiresIn() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExpiresIn
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value
// and a boolean to check if the value has been set.
func (o *CreateSandboxKey201Response) GetExpiresInOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresIn, true
}

// SetExpiresIn sets field value
func (o *CreateSandboxKey201Response) SetExpiresIn(v int32) {
	o.ExpiresIn = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *CreateSandboxKey201Response) GetExpiresAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *CreateSandboxKey201Response) GetExpiresAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *CreateSandboxKey201Response) SetExpiresAt(v string) {
	o.ExpiresAt = v
}

// GetScope returns the Scope field value
func (o *CreateSandboxKey201Response) GetScope() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *CreateSandboxKey201Response) GetScopeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scope, true
}

// SetScope sets field value
func (o *CreateSandboxKey201Response) SetScope(v string) {
	o.Scope = v
}

// GetProductionAccess returns the ProductionAccess field value
func (o *CreateSandboxKey201Response) GetProductionAccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ProductionAccess
}

// GetProductionAccessOk returns a tuple with the ProductionAccess field value
// and a boolean to check if the value has been set.
func (o *CreateSandboxKey201Response) GetProductionAccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProductionAccess, true
}

// SetProductionAccess sets field value
func (o *CreateSandboxKey201Response) SetProductionAccess(v bool) {
	o.ProductionAccess = v
}

// GetUse returns the Use field value
func (o *CreateSandboxKey201Response) GetUse() CreateSandboxKey201ResponseUse {
	if o == nil {
		var ret CreateSandboxKey201ResponseUse
		return ret
	}

	return o.Use
}

// GetUseOk returns a tuple with the Use field value
// and a boolean to check if the value has been set.
func (o *CreateSandboxKey201Response) GetUseOk() (*CreateSandboxKey201ResponseUse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Use, true
}

// SetUse sets field value
func (o *CreateSandboxKey201Response) SetUse(v CreateSandboxKey201ResponseUse) {
	o.Use = v
}

func (o CreateSandboxKey201Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSandboxKey201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["api_key"] = o.ApiKey
	toSerialize["token_type"] = o.TokenType
	toSerialize["expires_in"] = o.ExpiresIn
	toSerialize["expires_at"] = o.ExpiresAt
	toSerialize["scope"] = o.Scope
	toSerialize["production_access"] = o.ProductionAccess
	toSerialize["use"] = o.Use

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateSandboxKey201Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"api_key",
		"token_type",
		"expires_in",
		"expires_at",
		"scope",
		"production_access",
		"use",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateSandboxKey201Response := _CreateSandboxKey201Response{}

	err = json.Unmarshal(data, &varCreateSandboxKey201Response)

	if err != nil {
		return err
	}

	*o = CreateSandboxKey201Response(varCreateSandboxKey201Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "api_key")
		delete(additionalProperties, "token_type")
		delete(additionalProperties, "expires_in")
		delete(additionalProperties, "expires_at")
		delete(additionalProperties, "scope")
		delete(additionalProperties, "production_access")
		delete(additionalProperties, "use")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateSandboxKey201Response struct {
	value *CreateSandboxKey201Response
	isSet bool
}

func (v NullableCreateSandboxKey201Response) Get() *CreateSandboxKey201Response {
	return v.value
}

func (v *NullableCreateSandboxKey201Response) Set(val *CreateSandboxKey201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSandboxKey201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSandboxKey201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSandboxKey201Response(val *CreateSandboxKey201Response) *NullableCreateSandboxKey201Response {
	return &NullableCreateSandboxKey201Response{value: val, isSet: true}
}

func (v NullableCreateSandboxKey201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSandboxKey201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
