/*
Plainrouter Conversion API

Plainrouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the PlanCopyRead type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlanCopyRead{}

// PlanCopyRead struct for PlanCopyRead
type PlanCopyRead struct {
	Plan                 PlanCopyReadPlan `json:"plan"`
	AdditionalProperties map[string]interface{}
}

type _PlanCopyRead PlanCopyRead

// NewPlanCopyRead instantiates a new PlanCopyRead object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlanCopyRead(plan PlanCopyReadPlan) *PlanCopyRead {
	this := PlanCopyRead{}
	this.Plan = plan
	return &this
}

// NewPlanCopyReadWithDefaults instantiates a new PlanCopyRead object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlanCopyReadWithDefaults() *PlanCopyRead {
	this := PlanCopyRead{}
	return &this
}

// GetPlan returns the Plan field value
func (o *PlanCopyRead) GetPlan() PlanCopyReadPlan {
	if o == nil {
		var ret PlanCopyReadPlan
		return ret
	}

	return o.Plan
}

// GetPlanOk returns a tuple with the Plan field value
// and a boolean to check if the value has been set.
func (o *PlanCopyRead) GetPlanOk() (*PlanCopyReadPlan, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Plan, true
}

// SetPlan sets field value
func (o *PlanCopyRead) SetPlan(v PlanCopyReadPlan) {
	o.Plan = v
}

func (o PlanCopyRead) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlanCopyRead) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["plan"] = o.Plan

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PlanCopyRead) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"plan",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlanCopyRead := _PlanCopyRead{}

	err = json.Unmarshal(data, &varPlanCopyRead)

	if err != nil {
		return err
	}

	*o = PlanCopyRead(varPlanCopyRead)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "plan")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePlanCopyRead struct {
	value *PlanCopyRead
	isSet bool
}

func (v NullablePlanCopyRead) Get() *PlanCopyRead {
	return v.value
}

func (v *NullablePlanCopyRead) Set(val *PlanCopyRead) {
	v.value = val
	v.isSet = true
}

func (v NullablePlanCopyRead) IsSet() bool {
	return v.isSet
}

func (v *NullablePlanCopyRead) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlanCopyRead(val *PlanCopyRead) *NullablePlanCopyRead {
	return &NullablePlanCopyRead{value: val, isSet: true}
}

func (v NullablePlanCopyRead) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlanCopyRead) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
