/*
PlainRouter Conversion API

PlainRouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GetSandbox200ResponseTry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSandbox200ResponseTry{}

// GetSandbox200ResponseTry struct for GetSandbox200ResponseTry
type GetSandbox200ResponseTry struct {
	Method               string                       `json:"method"`
	Url                  string                       `json:"url"`
	ContentType          string                       `json:"content_type"`
	Body                 GetSandbox200ResponseTryBody `json:"body"`
	AdditionalProperties map[string]interface{}
}

type _GetSandbox200ResponseTry GetSandbox200ResponseTry

// NewGetSandbox200ResponseTry instantiates a new GetSandbox200ResponseTry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSandbox200ResponseTry(method string, url string, contentType string, body GetSandbox200ResponseTryBody) *GetSandbox200ResponseTry {
	this := GetSandbox200ResponseTry{}
	this.Method = method
	this.Url = url
	this.ContentType = contentType
	this.Body = body
	return &this
}

// NewGetSandbox200ResponseTryWithDefaults instantiates a new GetSandbox200ResponseTry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSandbox200ResponseTryWithDefaults() *GetSandbox200ResponseTry {
	this := GetSandbox200ResponseTry{}
	return &this
}

// GetMethod returns the Method field value
func (o *GetSandbox200ResponseTry) GetMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Method
}

// GetMethodOk returns a tuple with the Method field value
// and a boolean to check if the value has been set.
func (o *GetSandbox200ResponseTry) GetMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Method, true
}

// SetMethod sets field value
func (o *GetSandbox200ResponseTry) SetMethod(v string) {
	o.Method = v
}

// GetUrl returns the Url field value
func (o *GetSandbox200ResponseTry) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *GetSandbox200ResponseTry) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *GetSandbox200ResponseTry) SetUrl(v string) {
	o.Url = v
}

// GetContentType returns the ContentType field value
func (o *GetSandbox200ResponseTry) GetContentType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value
// and a boolean to check if the value has been set.
func (o *GetSandbox200ResponseTry) GetContentTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentType, true
}

// SetContentType sets field value
func (o *GetSandbox200ResponseTry) SetContentType(v string) {
	o.ContentType = v
}

// GetBody returns the Body field value
func (o *GetSandbox200ResponseTry) GetBody() GetSandbox200ResponseTryBody {
	if o == nil {
		var ret GetSandbox200ResponseTryBody
		return ret
	}

	return o.Body
}

// GetBodyOk returns a tuple with the Body field value
// and a boolean to check if the value has been set.
func (o *GetSandbox200ResponseTry) GetBodyOk() (*GetSandbox200ResponseTryBody, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Body, true
}

// SetBody sets field value
func (o *GetSandbox200ResponseTry) SetBody(v GetSandbox200ResponseTryBody) {
	o.Body = v
}

func (o GetSandbox200ResponseTry) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSandbox200ResponseTry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["method"] = o.Method
	toSerialize["url"] = o.Url
	toSerialize["content_type"] = o.ContentType
	toSerialize["body"] = o.Body

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetSandbox200ResponseTry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"method",
		"url",
		"content_type",
		"body",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetSandbox200ResponseTry := _GetSandbox200ResponseTry{}

	err = json.Unmarshal(data, &varGetSandbox200ResponseTry)

	if err != nil {
		return err
	}

	*o = GetSandbox200ResponseTry(varGetSandbox200ResponseTry)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "method")
		delete(additionalProperties, "url")
		delete(additionalProperties, "content_type")
		delete(additionalProperties, "body")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetSandbox200ResponseTry struct {
	value *GetSandbox200ResponseTry
	isSet bool
}

func (v NullableGetSandbox200ResponseTry) Get() *GetSandbox200ResponseTry {
	return v.value
}

func (v *NullableGetSandbox200ResponseTry) Set(val *GetSandbox200ResponseTry) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSandbox200ResponseTry) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSandbox200ResponseTry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSandbox200ResponseTry(val *GetSandbox200ResponseTry) *NullableGetSandbox200ResponseTry {
	return &NullableGetSandbox200ResponseTry{value: val, isSet: true}
}

func (v NullableGetSandbox200ResponseTry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSandbox200ResponseTry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
