/*
Plainrouter Conversion API

Plainrouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ActionDryRunReadDryRun type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActionDryRunReadDryRun{}

// ActionDryRunReadDryRun struct for ActionDryRunReadDryRun
type ActionDryRunReadDryRun struct {
	Actions              []ActionDryRunReadDryRunActionsInner `json:"actions"`
	AdditionalProperties map[string]interface{}
}

type _ActionDryRunReadDryRun ActionDryRunReadDryRun

// NewActionDryRunReadDryRun instantiates a new ActionDryRunReadDryRun object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActionDryRunReadDryRun(actions []ActionDryRunReadDryRunActionsInner) *ActionDryRunReadDryRun {
	this := ActionDryRunReadDryRun{}
	this.Actions = actions
	return &this
}

// NewActionDryRunReadDryRunWithDefaults instantiates a new ActionDryRunReadDryRun object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActionDryRunReadDryRunWithDefaults() *ActionDryRunReadDryRun {
	this := ActionDryRunReadDryRun{}
	return &this
}

// GetActions returns the Actions field value
func (o *ActionDryRunReadDryRun) GetActions() []ActionDryRunReadDryRunActionsInner {
	if o == nil {
		var ret []ActionDryRunReadDryRunActionsInner
		return ret
	}

	return o.Actions
}

// GetActionsOk returns a tuple with the Actions field value
// and a boolean to check if the value has been set.
func (o *ActionDryRunReadDryRun) GetActionsOk() ([]ActionDryRunReadDryRunActionsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Actions, true
}

// SetActions sets field value
func (o *ActionDryRunReadDryRun) SetActions(v []ActionDryRunReadDryRunActionsInner) {
	o.Actions = v
}

func (o ActionDryRunReadDryRun) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActionDryRunReadDryRun) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["actions"] = o.Actions

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ActionDryRunReadDryRun) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"actions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varActionDryRunReadDryRun := _ActionDryRunReadDryRun{}

	err = json.Unmarshal(data, &varActionDryRunReadDryRun)

	if err != nil {
		return err
	}

	*o = ActionDryRunReadDryRun(varActionDryRunReadDryRun)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "actions")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableActionDryRunReadDryRun struct {
	value *ActionDryRunReadDryRun
	isSet bool
}

func (v NullableActionDryRunReadDryRun) Get() *ActionDryRunReadDryRun {
	return v.value
}

func (v *NullableActionDryRunReadDryRun) Set(val *ActionDryRunReadDryRun) {
	v.value = val
	v.isSet = true
}

func (v NullableActionDryRunReadDryRun) IsSet() bool {
	return v.isSet
}

func (v *NullableActionDryRunReadDryRun) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActionDryRunReadDryRun(val *ActionDryRunReadDryRun) *NullableActionDryRunReadDryRun {
	return &NullableActionDryRunReadDryRun{value: val, isSet: true}
}

func (v NullableActionDryRunReadDryRun) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActionDryRunReadDryRun) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
