/*
Plainrouter Conversion API

Plainrouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ActionListReadMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActionListReadMeta{}

// ActionListReadMeta struct for ActionListReadMeta
type ActionListReadMeta struct {
	CurrentPage          int32 `json:"current_page"`
	LastPage             int32 `json:"last_page"`
	PerPage              int32 `json:"per_page"`
	Total                int32 `json:"total"`
	AdditionalProperties map[string]interface{}
}

type _ActionListReadMeta ActionListReadMeta

// NewActionListReadMeta instantiates a new ActionListReadMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActionListReadMeta(currentPage int32, lastPage int32, perPage int32, total int32) *ActionListReadMeta {
	this := ActionListReadMeta{}
	this.CurrentPage = currentPage
	this.LastPage = lastPage
	this.PerPage = perPage
	this.Total = total
	return &this
}

// NewActionListReadMetaWithDefaults instantiates a new ActionListReadMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActionListReadMetaWithDefaults() *ActionListReadMeta {
	this := ActionListReadMeta{}
	return &this
}

// GetCurrentPage returns the CurrentPage field value
func (o *ActionListReadMeta) GetCurrentPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CurrentPage
}

// GetCurrentPageOk returns a tuple with the CurrentPage field value
// and a boolean to check if the value has been set.
func (o *ActionListReadMeta) GetCurrentPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentPage, true
}

// SetCurrentPage sets field value
func (o *ActionListReadMeta) SetCurrentPage(v int32) {
	o.CurrentPage = v
}

// GetLastPage returns the LastPage field value
func (o *ActionListReadMeta) GetLastPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.LastPage
}

// GetLastPageOk returns a tuple with the LastPage field value
// and a boolean to check if the value has been set.
func (o *ActionListReadMeta) GetLastPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastPage, true
}

// SetLastPage sets field value
func (o *ActionListReadMeta) SetLastPage(v int32) {
	o.LastPage = v
}

// GetPerPage returns the PerPage field value
func (o *ActionListReadMeta) GetPerPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PerPage
}

// GetPerPageOk returns a tuple with the PerPage field value
// and a boolean to check if the value has been set.
func (o *ActionListReadMeta) GetPerPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PerPage, true
}

// SetPerPage sets field value
func (o *ActionListReadMeta) SetPerPage(v int32) {
	o.PerPage = v
}

// GetTotal returns the Total field value
func (o *ActionListReadMeta) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *ActionListReadMeta) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *ActionListReadMeta) SetTotal(v int32) {
	o.Total = v
}

func (o ActionListReadMeta) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActionListReadMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["current_page"] = o.CurrentPage
	toSerialize["last_page"] = o.LastPage
	toSerialize["per_page"] = o.PerPage
	toSerialize["total"] = o.Total

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ActionListReadMeta) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"current_page",
		"last_page",
		"per_page",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varActionListReadMeta := _ActionListReadMeta{}

	err = json.Unmarshal(data, &varActionListReadMeta)

	if err != nil {
		return err
	}

	*o = ActionListReadMeta(varActionListReadMeta)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "current_page")
		delete(additionalProperties, "last_page")
		delete(additionalProperties, "per_page")
		delete(additionalProperties, "total")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableActionListReadMeta struct {
	value *ActionListReadMeta
	isSet bool
}

func (v NullableActionListReadMeta) Get() *ActionListReadMeta {
	return v.value
}

func (v *NullableActionListReadMeta) Set(val *ActionListReadMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableActionListReadMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableActionListReadMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActionListReadMeta(val *ActionListReadMeta) *NullableActionListReadMeta {
	return &NullableActionListReadMeta{value: val, isSet: true}
}

func (v NullableActionListReadMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActionListReadMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
