/*
PlainRouter Conversion API

PlainRouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GetEvent200ResponseEventDeliveriesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEvent200ResponseEventDeliveriesInner{}

// GetEvent200ResponseEventDeliveriesInner struct for GetEvent200ResponseEventDeliveriesInner
type GetEvent200ResponseEventDeliveriesInner struct {
	Id                   int32          `json:"id"`
	SignalTrackerId      string         `json:"signal_tracker_id"`
	EventId              string         `json:"event_id"`
	DestinationId        NullableString `json:"destination_id"`
	Status               DeliveryStatus `json:"status"`
	IsTest               bool           `json:"is_test"`
	AttemptCount         int32          `json:"attempt_count"`
	LastError            interface{}    `json:"last_error"`
	PlatformResponse     interface{}    `json:"platform_response"`
	PlatformTraceId      NullableString `json:"platform_trace_id"`
	NextAttemptAt        NullableString `json:"next_attempt_at"`
	CreatedAt            string         `json:"created_at"`
	UpdatedAt            NullableString `json:"updated_at"`
	AdditionalProperties map[string]interface{}
}

type _GetEvent200ResponseEventDeliveriesInner GetEvent200ResponseEventDeliveriesInner

// NewGetEvent200ResponseEventDeliveriesInner instantiates a new GetEvent200ResponseEventDeliveriesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEvent200ResponseEventDeliveriesInner(id int32, signalTrackerId string, eventId string, destinationId NullableString, status DeliveryStatus, isTest bool, attemptCount int32, lastError interface{}, platformResponse interface{}, platformTraceId NullableString, nextAttemptAt NullableString, createdAt string, updatedAt NullableString) *GetEvent200ResponseEventDeliveriesInner {
	this := GetEvent200ResponseEventDeliveriesInner{}
	this.Id = id
	this.SignalTrackerId = signalTrackerId
	this.EventId = eventId
	this.DestinationId = destinationId
	this.Status = status
	this.IsTest = isTest
	this.AttemptCount = attemptCount
	this.LastError = lastError
	this.PlatformResponse = platformResponse
	this.PlatformTraceId = platformTraceId
	this.NextAttemptAt = nextAttemptAt
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewGetEvent200ResponseEventDeliveriesInnerWithDefaults instantiates a new GetEvent200ResponseEventDeliveriesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEvent200ResponseEventDeliveriesInnerWithDefaults() *GetEvent200ResponseEventDeliveriesInner {
	this := GetEvent200ResponseEventDeliveriesInner{}
	return &this
}

// GetId returns the Id field value
func (o *GetEvent200ResponseEventDeliveriesInner) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetEvent200ResponseEventDeliveriesInner) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetEvent200ResponseEventDeliveriesInner) SetId(v int32) {
	o.Id = v
}

// GetSignalTrackerId returns the SignalTrackerId field value
func (o *GetEvent200ResponseEventDeliveriesInner) GetSignalTrackerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SignalTrackerId
}

// GetSignalTrackerIdOk returns a tuple with the SignalTrackerId field value
// and a boolean to check if the value has been set.
func (o *GetEvent200ResponseEventDeliveriesInner) GetSignalTrackerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SignalTrackerId, true
}

// SetSignalTrackerId sets field value
func (o *GetEvent200ResponseEventDeliveriesInner) SetSignalTrackerId(v string) {
	o.SignalTrackerId = v
}

// GetEventId returns the EventId field value
func (o *GetEvent200ResponseEventDeliveriesInner) GetEventId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventId
}

// GetEventIdOk returns a tuple with the EventId field value
// and a boolean to check if the value has been set.
func (o *GetEvent200ResponseEventDeliveriesInner) GetEventIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventId, true
}

// SetEventId sets field value
func (o *GetEvent200ResponseEventDeliveriesInner) SetEventId(v string) {
	o.EventId = v
}

// GetDestinationId returns the DestinationId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetEvent200ResponseEventDeliveriesInner) GetDestinationId() string {
	if o == nil || o.DestinationId.Get() == nil {
		var ret string
		return ret
	}

	return *o.DestinationId.Get()
}

// GetDestinationIdOk returns a tuple with the DestinationId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetEvent200ResponseEventDeliveriesInner) GetDestinationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DestinationId.Get(), o.DestinationId.IsSet()
}

// SetDestinationId sets field value
func (o *GetEvent200ResponseEventDeliveriesInner) SetDestinationId(v string) {
	o.DestinationId.Set(&v)
}

// GetStatus returns the Status field value
func (o *GetEvent200ResponseEventDeliveriesInner) GetStatus() DeliveryStatus {
	if o == nil {
		var ret DeliveryStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetEvent200ResponseEventDeliveriesInner) GetStatusOk() (*DeliveryStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetEvent200ResponseEventDeliveriesInner) SetStatus(v DeliveryStatus) {
	o.Status = v
}

// GetIsTest returns the IsTest field value
func (o *GetEvent200ResponseEventDeliveriesInner) GetIsTest() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsTest
}

// GetIsTestOk returns a tuple with the IsTest field value
// and a boolean to check if the value has been set.
func (o *GetEvent200ResponseEventDeliveriesInner) GetIsTestOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsTest, true
}

// SetIsTest sets field value
func (o *GetEvent200ResponseEventDeliveriesInner) SetIsTest(v bool) {
	o.IsTest = v
}

// GetAttemptCount returns the AttemptCount field value
func (o *GetEvent200ResponseEventDeliveriesInner) GetAttemptCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AttemptCount
}

// GetAttemptCountOk returns a tuple with the AttemptCount field value
// and a boolean to check if the value has been set.
func (o *GetEvent200ResponseEventDeliveriesInner) GetAttemptCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttemptCount, true
}

// SetAttemptCount sets field value
func (o *GetEvent200ResponseEventDeliveriesInner) SetAttemptCount(v int32) {
	o.AttemptCount = v
}

// GetLastError returns the LastError field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *GetEvent200ResponseEventDeliveriesInner) GetLastError() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.LastError
}

// GetLastErrorOk returns a tuple with the LastError field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetEvent200ResponseEventDeliveriesInner) GetLastErrorOk() (*interface{}, bool) {
	if o == nil || IsNil(o.LastError) {
		return nil, false
	}
	return &o.LastError, true
}

// SetLastError sets field value
func (o *GetEvent200ResponseEventDeliveriesInner) SetLastError(v interface{}) {
	o.LastError = v
}

// GetPlatformResponse returns the PlatformResponse field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *GetEvent200ResponseEventDeliveriesInner) GetPlatformResponse() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.PlatformResponse
}

// GetPlatformResponseOk returns a tuple with the PlatformResponse field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetEvent200ResponseEventDeliveriesInner) GetPlatformResponseOk() (*interface{}, bool) {
	if o == nil || IsNil(o.PlatformResponse) {
		return nil, false
	}
	return &o.PlatformResponse, true
}

// SetPlatformResponse sets field value
func (o *GetEvent200ResponseEventDeliveriesInner) SetPlatformResponse(v interface{}) {
	o.PlatformResponse = v
}

// GetPlatformTraceId returns the PlatformTraceId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetEvent200ResponseEventDeliveriesInner) GetPlatformTraceId() string {
	if o == nil || o.PlatformTraceId.Get() == nil {
		var ret string
		return ret
	}

	return *o.PlatformTraceId.Get()
}

// GetPlatformTraceIdOk returns a tuple with the PlatformTraceId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetEvent200ResponseEventDeliveriesInner) GetPlatformTraceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PlatformTraceId.Get(), o.PlatformTraceId.IsSet()
}

// SetPlatformTraceId sets field value
func (o *GetEvent200ResponseEventDeliveriesInner) SetPlatformTraceId(v string) {
	o.PlatformTraceId.Set(&v)
}

// GetNextAttemptAt returns the NextAttemptAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetEvent200ResponseEventDeliveriesInner) GetNextAttemptAt() string {
	if o == nil || o.NextAttemptAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.NextAttemptAt.Get()
}

// GetNextAttemptAtOk returns a tuple with the NextAttemptAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetEvent200ResponseEventDeliveriesInner) GetNextAttemptAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextAttemptAt.Get(), o.NextAttemptAt.IsSet()
}

// SetNextAttemptAt sets field value
func (o *GetEvent200ResponseEventDeliveriesInner) SetNextAttemptAt(v string) {
	o.NextAttemptAt.Set(&v)
}

// GetCreatedAt returns the CreatedAt field value
func (o *GetEvent200ResponseEventDeliveriesInner) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GetEvent200ResponseEventDeliveriesInner) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GetEvent200ResponseEventDeliveriesInner) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetEvent200ResponseEventDeliveriesInner) GetUpdatedAt() string {
	if o == nil || o.UpdatedAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetEvent200ResponseEventDeliveriesInner) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// SetUpdatedAt sets field value
func (o *GetEvent200ResponseEventDeliveriesInner) SetUpdatedAt(v string) {
	o.UpdatedAt.Set(&v)
}

func (o GetEvent200ResponseEventDeliveriesInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEvent200ResponseEventDeliveriesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["signal_tracker_id"] = o.SignalTrackerId
	toSerialize["event_id"] = o.EventId
	toSerialize["destination_id"] = o.DestinationId.Get()
	toSerialize["status"] = o.Status
	toSerialize["is_test"] = o.IsTest
	toSerialize["attempt_count"] = o.AttemptCount
	if o.LastError != nil {
		toSerialize["last_error"] = o.LastError
	}
	if o.PlatformResponse != nil {
		toSerialize["platform_response"] = o.PlatformResponse
	}
	toSerialize["platform_trace_id"] = o.PlatformTraceId.Get()
	toSerialize["next_attempt_at"] = o.NextAttemptAt.Get()
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetEvent200ResponseEventDeliveriesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"signal_tracker_id",
		"event_id",
		"destination_id",
		"status",
		"is_test",
		"attempt_count",
		"last_error",
		"platform_response",
		"platform_trace_id",
		"next_attempt_at",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetEvent200ResponseEventDeliveriesInner := _GetEvent200ResponseEventDeliveriesInner{}

	err = json.Unmarshal(data, &varGetEvent200ResponseEventDeliveriesInner)

	if err != nil {
		return err
	}

	*o = GetEvent200ResponseEventDeliveriesInner(varGetEvent200ResponseEventDeliveriesInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "signal_tracker_id")
		delete(additionalProperties, "event_id")
		delete(additionalProperties, "destination_id")
		delete(additionalProperties, "status")
		delete(additionalProperties, "is_test")
		delete(additionalProperties, "attempt_count")
		delete(additionalProperties, "last_error")
		delete(additionalProperties, "platform_response")
		delete(additionalProperties, "platform_trace_id")
		delete(additionalProperties, "next_attempt_at")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetEvent200ResponseEventDeliveriesInner struct {
	value *GetEvent200ResponseEventDeliveriesInner
	isSet bool
}

func (v NullableGetEvent200ResponseEventDeliveriesInner) Get() *GetEvent200ResponseEventDeliveriesInner {
	return v.value
}

func (v *NullableGetEvent200ResponseEventDeliveriesInner) Set(val *GetEvent200ResponseEventDeliveriesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEvent200ResponseEventDeliveriesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEvent200ResponseEventDeliveriesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEvent200ResponseEventDeliveriesInner(val *GetEvent200ResponseEventDeliveriesInner) *NullableGetEvent200ResponseEventDeliveriesInner {
	return &NullableGetEvent200ResponseEventDeliveriesInner{value: val, isSet: true}
}

func (v NullableGetEvent200ResponseEventDeliveriesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEvent200ResponseEventDeliveriesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
