/*
Plainrouter Conversion API

Plainrouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ActionDetailRead type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActionDetailRead{}

// ActionDetailRead struct for ActionDetailRead
type ActionDetailRead struct {
	Data                 ActionReadItem `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _ActionDetailRead ActionDetailRead

// NewActionDetailRead instantiates a new ActionDetailRead object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActionDetailRead(data ActionReadItem) *ActionDetailRead {
	this := ActionDetailRead{}
	this.Data = data
	return &this
}

// NewActionDetailReadWithDefaults instantiates a new ActionDetailRead object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActionDetailReadWithDefaults() *ActionDetailRead {
	this := ActionDetailRead{}
	return &this
}

// GetData returns the Data field value
func (o *ActionDetailRead) GetData() ActionReadItem {
	if o == nil {
		var ret ActionReadItem
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ActionDetailRead) GetDataOk() (*ActionReadItem, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ActionDetailRead) SetData(v ActionReadItem) {
	o.Data = v
}

func (o ActionDetailRead) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActionDetailRead) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ActionDetailRead) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varActionDetailRead := _ActionDetailRead{}

	err = json.Unmarshal(data, &varActionDetailRead)

	if err != nil {
		return err
	}

	*o = ActionDetailRead(varActionDetailRead)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableActionDetailRead struct {
	value *ActionDetailRead
	isSet bool
}

func (v NullableActionDetailRead) Get() *ActionDetailRead {
	return v.value
}

func (v *NullableActionDetailRead) Set(val *ActionDetailRead) {
	v.value = val
	v.isSet = true
}

func (v NullableActionDetailRead) IsSet() bool {
	return v.isSet
}

func (v *NullableActionDetailRead) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActionDetailRead(val *ActionDetailRead) *NullableActionDetailRead {
	return &NullableActionDetailRead{value: val, isSet: true}
}

func (v NullableActionDetailRead) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActionDetailRead) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
