/*
Plainrouter Conversion API

Plainrouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SendTestPurchaseRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendTestPurchaseRequest{}

// SendTestPurchaseRequest struct for SendTestPurchaseRequest
type SendTestPurchaseRequest struct {
	Value                NullableString `json:"value,omitempty" validate:"regexp=^-?\\d+(?:\\.\\d+)?$"`
	Currency             NullableString `json:"currency,omitempty"`
	OrderId              NullableString `json:"order_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SendTestPurchaseRequest SendTestPurchaseRequest

// NewSendTestPurchaseRequest instantiates a new SendTestPurchaseRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendTestPurchaseRequest() *SendTestPurchaseRequest {
	this := SendTestPurchaseRequest{}
	return &this
}

// NewSendTestPurchaseRequestWithDefaults instantiates a new SendTestPurchaseRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendTestPurchaseRequestWithDefaults() *SendTestPurchaseRequest {
	this := SendTestPurchaseRequest{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SendTestPurchaseRequest) GetValue() string {
	if o == nil || IsNil(o.Value.Get()) {
		var ret string
		return ret
	}
	return *o.Value.Get()
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SendTestPurchaseRequest) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value.Get(), o.Value.IsSet()
}

// HasValue returns a boolean if a field has been set.
func (o *SendTestPurchaseRequest) HasValue() bool {
	if o != nil && o.Value.IsSet() {
		return true
	}

	return false
}

// SetValue gets a reference to the given NullableString and assigns it to the Value field.
func (o *SendTestPurchaseRequest) SetValue(v string) {
	o.Value.Set(&v)
}

// SetValueNil sets the value for Value to be an explicit nil
func (o *SendTestPurchaseRequest) SetValueNil() {
	o.Value.Set(nil)
}

// UnsetValue ensures that no value is present for Value, not even an explicit nil
func (o *SendTestPurchaseRequest) UnsetValue() {
	o.Value.Unset()
}

// GetCurrency returns the Currency field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SendTestPurchaseRequest) GetCurrency() string {
	if o == nil || IsNil(o.Currency.Get()) {
		var ret string
		return ret
	}
	return *o.Currency.Get()
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SendTestPurchaseRequest) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Currency.Get(), o.Currency.IsSet()
}

// HasCurrency returns a boolean if a field has been set.
func (o *SendTestPurchaseRequest) HasCurrency() bool {
	if o != nil && o.Currency.IsSet() {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given NullableString and assigns it to the Currency field.
func (o *SendTestPurchaseRequest) SetCurrency(v string) {
	o.Currency.Set(&v)
}

// SetCurrencyNil sets the value for Currency to be an explicit nil
func (o *SendTestPurchaseRequest) SetCurrencyNil() {
	o.Currency.Set(nil)
}

// UnsetCurrency ensures that no value is present for Currency, not even an explicit nil
func (o *SendTestPurchaseRequest) UnsetCurrency() {
	o.Currency.Unset()
}

// GetOrderId returns the OrderId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SendTestPurchaseRequest) GetOrderId() string {
	if o == nil || IsNil(o.OrderId.Get()) {
		var ret string
		return ret
	}
	return *o.OrderId.Get()
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SendTestPurchaseRequest) GetOrderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrderId.Get(), o.OrderId.IsSet()
}

// HasOrderId returns a boolean if a field has been set.
func (o *SendTestPurchaseRequest) HasOrderId() bool {
	if o != nil && o.OrderId.IsSet() {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given NullableString and assigns it to the OrderId field.
func (o *SendTestPurchaseRequest) SetOrderId(v string) {
	o.OrderId.Set(&v)
}

// SetOrderIdNil sets the value for OrderId to be an explicit nil
func (o *SendTestPurchaseRequest) SetOrderIdNil() {
	o.OrderId.Set(nil)
}

// UnsetOrderId ensures that no value is present for OrderId, not even an explicit nil
func (o *SendTestPurchaseRequest) UnsetOrderId() {
	o.OrderId.Unset()
}

func (o SendTestPurchaseRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendTestPurchaseRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Value.IsSet() {
		toSerialize["value"] = o.Value.Get()
	}
	if o.Currency.IsSet() {
		toSerialize["currency"] = o.Currency.Get()
	}
	if o.OrderId.IsSet() {
		toSerialize["order_id"] = o.OrderId.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SendTestPurchaseRequest) UnmarshalJSON(data []byte) (err error) {
	varSendTestPurchaseRequest := _SendTestPurchaseRequest{}

	err = json.Unmarshal(data, &varSendTestPurchaseRequest)

	if err != nil {
		return err
	}

	*o = SendTestPurchaseRequest(varSendTestPurchaseRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "value")
		delete(additionalProperties, "currency")
		delete(additionalProperties, "order_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSendTestPurchaseRequest struct {
	value *SendTestPurchaseRequest
	isSet bool
}

func (v NullableSendTestPurchaseRequest) Get() *SendTestPurchaseRequest {
	return v.value
}

func (v *NullableSendTestPurchaseRequest) Set(val *SendTestPurchaseRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSendTestPurchaseRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSendTestPurchaseRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendTestPurchaseRequest(val *SendTestPurchaseRequest) *NullableSendTestPurchaseRequest {
	return &NullableSendTestPurchaseRequest{value: val, isSet: true}
}

func (v NullableSendTestPurchaseRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendTestPurchaseRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
