/*
Plainrouter Conversion API

Plainrouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GetSandbox200ResponseSelfServeKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSandbox200ResponseSelfServeKey{}

// GetSandbox200ResponseSelfServeKey struct for GetSandbox200ResponseSelfServeKey
type GetSandbox200ResponseSelfServeKey struct {
	Method                 string                                     `json:"method"`
	Url                    string                                     `json:"url"`
	AuthenticationRequired bool                                       `json:"authentication_required"`
	Description            string                                     `json:"description"`
	IssuedKey              GetSandbox200ResponseSelfServeKeyIssuedKey `json:"issued_key"`
	AdditionalProperties   map[string]interface{}
}

type _GetSandbox200ResponseSelfServeKey GetSandbox200ResponseSelfServeKey

// NewGetSandbox200ResponseSelfServeKey instantiates a new GetSandbox200ResponseSelfServeKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSandbox200ResponseSelfServeKey(method string, url string, authenticationRequired bool, description string, issuedKey GetSandbox200ResponseSelfServeKeyIssuedKey) *GetSandbox200ResponseSelfServeKey {
	this := GetSandbox200ResponseSelfServeKey{}
	this.Method = method
	this.Url = url
	this.AuthenticationRequired = authenticationRequired
	this.Description = description
	this.IssuedKey = issuedKey
	return &this
}

// NewGetSandbox200ResponseSelfServeKeyWithDefaults instantiates a new GetSandbox200ResponseSelfServeKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSandbox200ResponseSelfServeKeyWithDefaults() *GetSandbox200ResponseSelfServeKey {
	this := GetSandbox200ResponseSelfServeKey{}
	return &this
}

// GetMethod returns the Method field value
func (o *GetSandbox200ResponseSelfServeKey) GetMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Method
}

// GetMethodOk returns a tuple with the Method field value
// and a boolean to check if the value has been set.
func (o *GetSandbox200ResponseSelfServeKey) GetMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Method, true
}

// SetMethod sets field value
func (o *GetSandbox200ResponseSelfServeKey) SetMethod(v string) {
	o.Method = v
}

// GetUrl returns the Url field value
func (o *GetSandbox200ResponseSelfServeKey) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *GetSandbox200ResponseSelfServeKey) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *GetSandbox200ResponseSelfServeKey) SetUrl(v string) {
	o.Url = v
}

// GetAuthenticationRequired returns the AuthenticationRequired field value
func (o *GetSandbox200ResponseSelfServeKey) GetAuthenticationRequired() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AuthenticationRequired
}

// GetAuthenticationRequiredOk returns a tuple with the AuthenticationRequired field value
// and a boolean to check if the value has been set.
func (o *GetSandbox200ResponseSelfServeKey) GetAuthenticationRequiredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthenticationRequired, true
}

// SetAuthenticationRequired sets field value
func (o *GetSandbox200ResponseSelfServeKey) SetAuthenticationRequired(v bool) {
	o.AuthenticationRequired = v
}

// GetDescription returns the Description field value
func (o *GetSandbox200ResponseSelfServeKey) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *GetSandbox200ResponseSelfServeKey) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *GetSandbox200ResponseSelfServeKey) SetDescription(v string) {
	o.Description = v
}

// GetIssuedKey returns the IssuedKey field value
func (o *GetSandbox200ResponseSelfServeKey) GetIssuedKey() GetSandbox200ResponseSelfServeKeyIssuedKey {
	if o == nil {
		var ret GetSandbox200ResponseSelfServeKeyIssuedKey
		return ret
	}

	return o.IssuedKey
}

// GetIssuedKeyOk returns a tuple with the IssuedKey field value
// and a boolean to check if the value has been set.
func (o *GetSandbox200ResponseSelfServeKey) GetIssuedKeyOk() (*GetSandbox200ResponseSelfServeKeyIssuedKey, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IssuedKey, true
}

// SetIssuedKey sets field value
func (o *GetSandbox200ResponseSelfServeKey) SetIssuedKey(v GetSandbox200ResponseSelfServeKeyIssuedKey) {
	o.IssuedKey = v
}

func (o GetSandbox200ResponseSelfServeKey) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSandbox200ResponseSelfServeKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["method"] = o.Method
	toSerialize["url"] = o.Url
	toSerialize["authentication_required"] = o.AuthenticationRequired
	toSerialize["description"] = o.Description
	toSerialize["issued_key"] = o.IssuedKey

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetSandbox200ResponseSelfServeKey) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"method",
		"url",
		"authentication_required",
		"description",
		"issued_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetSandbox200ResponseSelfServeKey := _GetSandbox200ResponseSelfServeKey{}

	err = json.Unmarshal(data, &varGetSandbox200ResponseSelfServeKey)

	if err != nil {
		return err
	}

	*o = GetSandbox200ResponseSelfServeKey(varGetSandbox200ResponseSelfServeKey)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "method")
		delete(additionalProperties, "url")
		delete(additionalProperties, "authentication_required")
		delete(additionalProperties, "description")
		delete(additionalProperties, "issued_key")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetSandbox200ResponseSelfServeKey struct {
	value *GetSandbox200ResponseSelfServeKey
	isSet bool
}

func (v NullableGetSandbox200ResponseSelfServeKey) Get() *GetSandbox200ResponseSelfServeKey {
	return v.value
}

func (v *NullableGetSandbox200ResponseSelfServeKey) Set(val *GetSandbox200ResponseSelfServeKey) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSandbox200ResponseSelfServeKey) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSandbox200ResponseSelfServeKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSandbox200ResponseSelfServeKey(val *GetSandbox200ResponseSelfServeKey) *NullableGetSandbox200ResponseSelfServeKey {
	return &NullableGetSandbox200ResponseSelfServeKey{value: val, isSet: true}
}

func (v NullableGetSandbox200ResponseSelfServeKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSandbox200ResponseSelfServeKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
