/*
Plainrouter Conversion API

Plainrouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the PlanCopyReadPlan type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlanCopyReadPlan{}

// PlanCopyReadPlan struct for PlanCopyReadPlan
type PlanCopyReadPlan struct {
	Id                   string      `json:"id"`
	PlatformAdAccountId  int32       `json:"platform_ad_account_id"`
	Status               string      `json:"status"`
	BudgetAmountMinor    int32       `json:"budget_amount_minor"`
	ValidationResult     interface{} `json:"validation_result"`
	ValidatedAt          interface{} `json:"validated_at"`
	ApprovalId           interface{} `json:"approval_id"`
	AdditionalProperties map[string]interface{}
}

type _PlanCopyReadPlan PlanCopyReadPlan

// NewPlanCopyReadPlan instantiates a new PlanCopyReadPlan object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlanCopyReadPlan(id string, platformAdAccountId int32, status string, budgetAmountMinor int32, validationResult interface{}, validatedAt interface{}, approvalId interface{}) *PlanCopyReadPlan {
	this := PlanCopyReadPlan{}
	this.Id = id
	this.PlatformAdAccountId = platformAdAccountId
	this.Status = status
	this.BudgetAmountMinor = budgetAmountMinor
	this.ValidationResult = validationResult
	this.ValidatedAt = validatedAt
	this.ApprovalId = approvalId
	return &this
}

// NewPlanCopyReadPlanWithDefaults instantiates a new PlanCopyReadPlan object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlanCopyReadPlanWithDefaults() *PlanCopyReadPlan {
	this := PlanCopyReadPlan{}
	return &this
}

// GetId returns the Id field value
func (o *PlanCopyReadPlan) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PlanCopyReadPlan) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PlanCopyReadPlan) SetId(v string) {
	o.Id = v
}

// GetPlatformAdAccountId returns the PlatformAdAccountId field value
func (o *PlanCopyReadPlan) GetPlatformAdAccountId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PlatformAdAccountId
}

// GetPlatformAdAccountIdOk returns a tuple with the PlatformAdAccountId field value
// and a boolean to check if the value has been set.
func (o *PlanCopyReadPlan) GetPlatformAdAccountIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlatformAdAccountId, true
}

// SetPlatformAdAccountId sets field value
func (o *PlanCopyReadPlan) SetPlatformAdAccountId(v int32) {
	o.PlatformAdAccountId = v
}

// GetStatus returns the Status field value
func (o *PlanCopyReadPlan) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *PlanCopyReadPlan) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *PlanCopyReadPlan) SetStatus(v string) {
	o.Status = v
}

// GetBudgetAmountMinor returns the BudgetAmountMinor field value
func (o *PlanCopyReadPlan) GetBudgetAmountMinor() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BudgetAmountMinor
}

// GetBudgetAmountMinorOk returns a tuple with the BudgetAmountMinor field value
// and a boolean to check if the value has been set.
func (o *PlanCopyReadPlan) GetBudgetAmountMinorOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BudgetAmountMinor, true
}

// SetBudgetAmountMinor sets field value
func (o *PlanCopyReadPlan) SetBudgetAmountMinor(v int32) {
	o.BudgetAmountMinor = v
}

// GetValidationResult returns the ValidationResult field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *PlanCopyReadPlan) GetValidationResult() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.ValidationResult
}

// GetValidationResultOk returns a tuple with the ValidationResult field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlanCopyReadPlan) GetValidationResultOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ValidationResult) {
		return nil, false
	}
	return &o.ValidationResult, true
}

// SetValidationResult sets field value
func (o *PlanCopyReadPlan) SetValidationResult(v interface{}) {
	o.ValidationResult = v
}

// GetValidatedAt returns the ValidatedAt field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *PlanCopyReadPlan) GetValidatedAt() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.ValidatedAt
}

// GetValidatedAtOk returns a tuple with the ValidatedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlanCopyReadPlan) GetValidatedAtOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ValidatedAt) {
		return nil, false
	}
	return &o.ValidatedAt, true
}

// SetValidatedAt sets field value
func (o *PlanCopyReadPlan) SetValidatedAt(v interface{}) {
	o.ValidatedAt = v
}

// GetApprovalId returns the ApprovalId field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *PlanCopyReadPlan) GetApprovalId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.ApprovalId
}

// GetApprovalIdOk returns a tuple with the ApprovalId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlanCopyReadPlan) GetApprovalIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ApprovalId) {
		return nil, false
	}
	return &o.ApprovalId, true
}

// SetApprovalId sets field value
func (o *PlanCopyReadPlan) SetApprovalId(v interface{}) {
	o.ApprovalId = v
}

func (o PlanCopyReadPlan) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlanCopyReadPlan) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["platform_ad_account_id"] = o.PlatformAdAccountId
	toSerialize["status"] = o.Status
	toSerialize["budget_amount_minor"] = o.BudgetAmountMinor
	if o.ValidationResult != nil {
		toSerialize["validation_result"] = o.ValidationResult
	}
	if o.ValidatedAt != nil {
		toSerialize["validated_at"] = o.ValidatedAt
	}
	if o.ApprovalId != nil {
		toSerialize["approval_id"] = o.ApprovalId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PlanCopyReadPlan) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"platform_ad_account_id",
		"status",
		"budget_amount_minor",
		"validation_result",
		"validated_at",
		"approval_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlanCopyReadPlan := _PlanCopyReadPlan{}

	err = json.Unmarshal(data, &varPlanCopyReadPlan)

	if err != nil {
		return err
	}

	*o = PlanCopyReadPlan(varPlanCopyReadPlan)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "platform_ad_account_id")
		delete(additionalProperties, "status")
		delete(additionalProperties, "budget_amount_minor")
		delete(additionalProperties, "validation_result")
		delete(additionalProperties, "validated_at")
		delete(additionalProperties, "approval_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePlanCopyReadPlan struct {
	value *PlanCopyReadPlan
	isSet bool
}

func (v NullablePlanCopyReadPlan) Get() *PlanCopyReadPlan {
	return v.value
}

func (v *NullablePlanCopyReadPlan) Set(val *PlanCopyReadPlan) {
	v.value = val
	v.isSet = true
}

func (v NullablePlanCopyReadPlan) IsSet() bool {
	return v.isSet
}

func (v *NullablePlanCopyReadPlan) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlanCopyReadPlan(val *PlanCopyReadPlan) *NullablePlanCopyReadPlan {
	return &NullablePlanCopyReadPlan{value: val, isSet: true}
}

func (v NullablePlanCopyReadPlan) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlanCopyReadPlan) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
