/*
Plainrouter Conversion API

Plainrouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GetEmqReport200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEmqReport200Response{}

// GetEmqReport200Response struct for GetEmqReport200Response
type GetEmqReport200Response struct {
	Snapshots            []GetEmqReport200ResponseSnapshotsInner `json:"snapshots"`
	AdditionalProperties map[string]interface{}
}

type _GetEmqReport200Response GetEmqReport200Response

// NewGetEmqReport200Response instantiates a new GetEmqReport200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEmqReport200Response(snapshots []GetEmqReport200ResponseSnapshotsInner) *GetEmqReport200Response {
	this := GetEmqReport200Response{}
	this.Snapshots = snapshots
	return &this
}

// NewGetEmqReport200ResponseWithDefaults instantiates a new GetEmqReport200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEmqReport200ResponseWithDefaults() *GetEmqReport200Response {
	this := GetEmqReport200Response{}
	return &this
}

// GetSnapshots returns the Snapshots field value
func (o *GetEmqReport200Response) GetSnapshots() []GetEmqReport200ResponseSnapshotsInner {
	if o == nil {
		var ret []GetEmqReport200ResponseSnapshotsInner
		return ret
	}

	return o.Snapshots
}

// GetSnapshotsOk returns a tuple with the Snapshots field value
// and a boolean to check if the value has been set.
func (o *GetEmqReport200Response) GetSnapshotsOk() ([]GetEmqReport200ResponseSnapshotsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Snapshots, true
}

// SetSnapshots sets field value
func (o *GetEmqReport200Response) SetSnapshots(v []GetEmqReport200ResponseSnapshotsInner) {
	o.Snapshots = v
}

func (o GetEmqReport200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEmqReport200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["snapshots"] = o.Snapshots

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetEmqReport200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"snapshots",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetEmqReport200Response := _GetEmqReport200Response{}

	err = json.Unmarshal(data, &varGetEmqReport200Response)

	if err != nil {
		return err
	}

	*o = GetEmqReport200Response(varGetEmqReport200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "snapshots")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetEmqReport200Response struct {
	value *GetEmqReport200Response
	isSet bool
}

func (v NullableGetEmqReport200Response) Get() *GetEmqReport200Response {
	return v.value
}

func (v *NullableGetEmqReport200Response) Set(val *GetEmqReport200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEmqReport200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEmqReport200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEmqReport200Response(val *GetEmqReport200Response) *NullableGetEmqReport200Response {
	return &NullableGetEmqReport200Response{value: val, isSet: true}
}

func (v NullableGetEmqReport200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEmqReport200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
