/*
PlainRouter Conversion API

PlainRouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// DestinationCredentialSource the model 'DestinationCredentialSource'
type DestinationCredentialSource string

// List of DestinationCredentialSource
const (
	DESTINATIONCREDENTIALSOURCE_OAUTH_CONNECTION         DestinationCredentialSource = "oauth_connection"
	DESTINATIONCREDENTIALSOURCE_MANAGED_TOKEN            DestinationCredentialSource = "managed_token"
	DESTINATIONCREDENTIALSOURCE_UNKNOWN_DEFAULT_OPEN_API DestinationCredentialSource = "unknown_default_open_api"
)

// All allowed values of DestinationCredentialSource enum
var AllowedDestinationCredentialSourceEnumValues = []DestinationCredentialSource{
	"oauth_connection",
	"managed_token",
	"unknown_default_open_api",
}

func (v *DestinationCredentialSource) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DestinationCredentialSource(value)
	for _, existing := range AllowedDestinationCredentialSourceEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = DESTINATIONCREDENTIALSOURCE_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewDestinationCredentialSourceFromValue returns a pointer to a valid DestinationCredentialSource
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDestinationCredentialSourceFromValue(v string) (*DestinationCredentialSource, error) {
	ev := DestinationCredentialSource(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DestinationCredentialSource: valid values are %v", v, AllowedDestinationCredentialSourceEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DestinationCredentialSource) IsValid() bool {
	for _, existing := range AllowedDestinationCredentialSourceEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to DestinationCredentialSource value
func (v DestinationCredentialSource) Ptr() *DestinationCredentialSource {
	return &v
}

type NullableDestinationCredentialSource struct {
	value *DestinationCredentialSource
	isSet bool
}

func (v NullableDestinationCredentialSource) Get() *DestinationCredentialSource {
	return v.value
}

func (v *NullableDestinationCredentialSource) Set(val *DestinationCredentialSource) {
	v.value = val
	v.isSet = true
}

func (v NullableDestinationCredentialSource) IsSet() bool {
	return v.isSet
}

func (v *NullableDestinationCredentialSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDestinationCredentialSource(val *DestinationCredentialSource) *NullableDestinationCredentialSource {
	return &NullableDestinationCredentialSource{value: val, isSet: true}
}

func (v NullableDestinationCredentialSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDestinationCredentialSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
