/*
Plainrouter Conversion API

Plainrouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ActionListRead type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActionListRead{}

// ActionListRead struct for ActionListRead
type ActionListRead struct {
	Data                 []ActionReadItem   `json:"data"`
	Meta                 ActionListReadMeta `json:"meta"`
	AdditionalProperties map[string]interface{}
}

type _ActionListRead ActionListRead

// NewActionListRead instantiates a new ActionListRead object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActionListRead(data []ActionReadItem, meta ActionListReadMeta) *ActionListRead {
	this := ActionListRead{}
	this.Data = data
	this.Meta = meta
	return &this
}

// NewActionListReadWithDefaults instantiates a new ActionListRead object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActionListReadWithDefaults() *ActionListRead {
	this := ActionListRead{}
	return &this
}

// GetData returns the Data field value
func (o *ActionListRead) GetData() []ActionReadItem {
	if o == nil {
		var ret []ActionReadItem
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ActionListRead) GetDataOk() ([]ActionReadItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ActionListRead) SetData(v []ActionReadItem) {
	o.Data = v
}

// GetMeta returns the Meta field value
func (o *ActionListRead) GetMeta() ActionListReadMeta {
	if o == nil {
		var ret ActionListReadMeta
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *ActionListRead) GetMetaOk() (*ActionListReadMeta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *ActionListRead) SetMeta(v ActionListReadMeta) {
	o.Meta = v
}

func (o ActionListRead) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActionListRead) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["meta"] = o.Meta

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ActionListRead) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"meta",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varActionListRead := _ActionListRead{}

	err = json.Unmarshal(data, &varActionListRead)

	if err != nil {
		return err
	}

	*o = ActionListRead(varActionListRead)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "meta")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableActionListRead struct {
	value *ActionListRead
	isSet bool
}

func (v NullableActionListRead) Get() *ActionListRead {
	return v.value
}

func (v *NullableActionListRead) Set(val *ActionListRead) {
	v.value = val
	v.isSet = true
}

func (v NullableActionListRead) IsSet() bool {
	return v.isSet
}

func (v *NullableActionListRead) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActionListRead(val *ActionListRead) *NullableActionListRead {
	return &NullableActionListRead{value: val, isSet: true}
}

func (v NullableActionListRead) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActionListRead) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
