/*
Plainrouter Conversion API

Plainrouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ActionProposalRead type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActionProposalRead{}

// ActionProposalRead struct for ActionProposalRead
type ActionProposalRead struct {
	Proposal             ActionProposalReadProposal `json:"proposal"`
	AdditionalProperties map[string]interface{}
}

type _ActionProposalRead ActionProposalRead

// NewActionProposalRead instantiates a new ActionProposalRead object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActionProposalRead(proposal ActionProposalReadProposal) *ActionProposalRead {
	this := ActionProposalRead{}
	this.Proposal = proposal
	return &this
}

// NewActionProposalReadWithDefaults instantiates a new ActionProposalRead object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActionProposalReadWithDefaults() *ActionProposalRead {
	this := ActionProposalRead{}
	return &this
}

// GetProposal returns the Proposal field value
func (o *ActionProposalRead) GetProposal() ActionProposalReadProposal {
	if o == nil {
		var ret ActionProposalReadProposal
		return ret
	}

	return o.Proposal
}

// GetProposalOk returns a tuple with the Proposal field value
// and a boolean to check if the value has been set.
func (o *ActionProposalRead) GetProposalOk() (*ActionProposalReadProposal, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Proposal, true
}

// SetProposal sets field value
func (o *ActionProposalRead) SetProposal(v ActionProposalReadProposal) {
	o.Proposal = v
}

func (o ActionProposalRead) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActionProposalRead) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["proposal"] = o.Proposal

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ActionProposalRead) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"proposal",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varActionProposalRead := _ActionProposalRead{}

	err = json.Unmarshal(data, &varActionProposalRead)

	if err != nil {
		return err
	}

	*o = ActionProposalRead(varActionProposalRead)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "proposal")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableActionProposalRead struct {
	value *ActionProposalRead
	isSet bool
}

func (v NullableActionProposalRead) Get() *ActionProposalRead {
	return v.value
}

func (v *NullableActionProposalRead) Set(val *ActionProposalRead) {
	v.value = val
	v.isSet = true
}

func (v NullableActionProposalRead) IsSet() bool {
	return v.isSet
}

func (v *NullableActionProposalRead) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActionProposalRead(val *ActionProposalRead) *NullableActionProposalRead {
	return &NullableActionProposalRead{value: val, isSet: true}
}

func (v NullableActionProposalRead) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActionProposalRead) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
