/*
PlainRouter Conversion API

PlainRouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// GetReconciliationReport200ResponseReportsInnerEventCountsAccepted struct for GetReconciliationReport200ResponseReportsInnerEventCountsAccepted
type GetReconciliationReport200ResponseReportsInnerEventCountsAccepted struct {
	ArrayOfAny          *[]interface{}
	MapmapOfStringint32 *map[string]int32
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *GetReconciliationReport200ResponseReportsInnerEventCountsAccepted) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into ArrayOfAny
	err = json.Unmarshal(data, &dst.ArrayOfAny)
	if err == nil {
		jsonArrayOfAny, _ := json.Marshal(dst.ArrayOfAny)
		if string(jsonArrayOfAny) == "{}" { // empty struct
			dst.ArrayOfAny = nil
		} else {
			return nil // data stored in dst.ArrayOfAny, return on the first match
		}
	} else {
		dst.ArrayOfAny = nil
	}

	// try to unmarshal JSON data into MapmapOfStringint32
	err = json.Unmarshal(data, &dst.MapmapOfStringint32)
	if err == nil {
		jsonMapmapOfStringint32, _ := json.Marshal(dst.MapmapOfStringint32)
		if string(jsonMapmapOfStringint32) == "{}" { // empty struct
			dst.MapmapOfStringint32 = nil
		} else {
			return nil // data stored in dst.MapmapOfStringint32, return on the first match
		}
	} else {
		dst.MapmapOfStringint32 = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(GetReconciliationReport200ResponseReportsInnerEventCountsAccepted)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetReconciliationReport200ResponseReportsInnerEventCountsAccepted) MarshalJSON() ([]byte, error) {
	if src.ArrayOfAny != nil {
		return json.Marshal(&src.ArrayOfAny)
	}

	if src.MapmapOfStringint32 != nil {
		return json.Marshal(&src.MapmapOfStringint32)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableGetReconciliationReport200ResponseReportsInnerEventCountsAccepted struct {
	value *GetReconciliationReport200ResponseReportsInnerEventCountsAccepted
	isSet bool
}

func (v NullableGetReconciliationReport200ResponseReportsInnerEventCountsAccepted) Get() *GetReconciliationReport200ResponseReportsInnerEventCountsAccepted {
	return v.value
}

func (v *NullableGetReconciliationReport200ResponseReportsInnerEventCountsAccepted) Set(val *GetReconciliationReport200ResponseReportsInnerEventCountsAccepted) {
	v.value = val
	v.isSet = true
}

func (v NullableGetReconciliationReport200ResponseReportsInnerEventCountsAccepted) IsSet() bool {
	return v.isSet
}

func (v *NullableGetReconciliationReport200ResponseReportsInnerEventCountsAccepted) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetReconciliationReport200ResponseReportsInnerEventCountsAccepted(val *GetReconciliationReport200ResponseReportsInnerEventCountsAccepted) *NullableGetReconciliationReport200ResponseReportsInnerEventCountsAccepted {
	return &NullableGetReconciliationReport200ResponseReportsInnerEventCountsAccepted{value: val, isSet: true}
}

func (v NullableGetReconciliationReport200ResponseReportsInnerEventCountsAccepted) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetReconciliationReport200ResponseReportsInnerEventCountsAccepted) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
