/*
Plainrouter Conversion API

Plainrouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ActionProposalReadProposalProposedBy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActionProposalReadProposalProposedBy{}

// ActionProposalReadProposalProposedBy struct for ActionProposalReadProposalProposedBy
type ActionProposalReadProposalProposedBy struct {
	Type                 string         `json:"type"`
	Id                   string         `json:"id"`
	Name                 NullableString `json:"name"`
	AdditionalProperties map[string]interface{}
}

type _ActionProposalReadProposalProposedBy ActionProposalReadProposalProposedBy

// NewActionProposalReadProposalProposedBy instantiates a new ActionProposalReadProposalProposedBy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActionProposalReadProposalProposedBy(type_ string, id string, name NullableString) *ActionProposalReadProposalProposedBy {
	this := ActionProposalReadProposalProposedBy{}
	this.Type = type_
	this.Id = id
	this.Name = name
	return &this
}

// NewActionProposalReadProposalProposedByWithDefaults instantiates a new ActionProposalReadProposalProposedBy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActionProposalReadProposalProposedByWithDefaults() *ActionProposalReadProposalProposedBy {
	this := ActionProposalReadProposalProposedBy{}
	return &this
}

// GetType returns the Type field value
func (o *ActionProposalReadProposalProposedBy) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ActionProposalReadProposalProposedBy) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ActionProposalReadProposalProposedBy) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *ActionProposalReadProposalProposedBy) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ActionProposalReadProposalProposedBy) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ActionProposalReadProposalProposedBy) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ActionProposalReadProposalProposedBy) GetName() string {
	if o == nil || o.Name.Get() == nil {
		var ret string
		return ret
	}

	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ActionProposalReadProposalProposedBy) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// SetName sets field value
func (o *ActionProposalReadProposalProposedBy) SetName(v string) {
	o.Name.Set(&v)
}

func (o ActionProposalReadProposalProposedBy) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActionProposalReadProposalProposedBy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ActionProposalReadProposalProposedBy) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varActionProposalReadProposalProposedBy := _ActionProposalReadProposalProposedBy{}

	err = json.Unmarshal(data, &varActionProposalReadProposalProposedBy)

	if err != nil {
		return err
	}

	*o = ActionProposalReadProposalProposedBy(varActionProposalReadProposalProposedBy)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableActionProposalReadProposalProposedBy struct {
	value *ActionProposalReadProposalProposedBy
	isSet bool
}

func (v NullableActionProposalReadProposalProposedBy) Get() *ActionProposalReadProposalProposedBy {
	return v.value
}

func (v *NullableActionProposalReadProposalProposedBy) Set(val *ActionProposalReadProposalProposedBy) {
	v.value = val
	v.isSet = true
}

func (v NullableActionProposalReadProposalProposedBy) IsSet() bool {
	return v.isSet
}

func (v *NullableActionProposalReadProposalProposedBy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActionProposalReadProposalProposedBy(val *ActionProposalReadProposalProposedBy) *NullableActionProposalReadProposalProposedBy {
	return &NullableActionProposalReadProposalProposedBy{value: val, isSet: true}
}

func (v NullableActionProposalReadProposalProposedBy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActionProposalReadProposalProposedBy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
