/*
Plainrouter Conversion API

Plainrouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ActionPolicyRead type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActionPolicyRead{}

// ActionPolicyRead struct for ActionPolicyRead
type ActionPolicyRead struct {
	Data                 ActionPolicyReadData `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _ActionPolicyRead ActionPolicyRead

// NewActionPolicyRead instantiates a new ActionPolicyRead object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActionPolicyRead(data ActionPolicyReadData) *ActionPolicyRead {
	this := ActionPolicyRead{}
	this.Data = data
	return &this
}

// NewActionPolicyReadWithDefaults instantiates a new ActionPolicyRead object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActionPolicyReadWithDefaults() *ActionPolicyRead {
	this := ActionPolicyRead{}
	return &this
}

// GetData returns the Data field value
func (o *ActionPolicyRead) GetData() ActionPolicyReadData {
	if o == nil {
		var ret ActionPolicyReadData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ActionPolicyRead) GetDataOk() (*ActionPolicyReadData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ActionPolicyRead) SetData(v ActionPolicyReadData) {
	o.Data = v
}

func (o ActionPolicyRead) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActionPolicyRead) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ActionPolicyRead) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varActionPolicyRead := _ActionPolicyRead{}

	err = json.Unmarshal(data, &varActionPolicyRead)

	if err != nil {
		return err
	}

	*o = ActionPolicyRead(varActionPolicyRead)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableActionPolicyRead struct {
	value *ActionPolicyRead
	isSet bool
}

func (v NullableActionPolicyRead) Get() *ActionPolicyRead {
	return v.value
}

func (v *NullableActionPolicyRead) Set(val *ActionPolicyRead) {
	v.value = val
	v.isSet = true
}

func (v NullableActionPolicyRead) IsSet() bool {
	return v.isSet
}

func (v *NullableActionPolicyRead) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActionPolicyRead(val *ActionPolicyRead) *NullableActionPolicyRead {
	return &NullableActionPolicyRead{value: val, isSet: true}
}

func (v NullableActionPolicyRead) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActionPolicyRead) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
