/*
Plainrouter Conversion API

Plainrouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ActionProposalInputActionsInnerAnyOf10Params type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActionProposalInputActionsInnerAnyOf10Params{}

// ActionProposalInputActionsInnerAnyOf10Params struct for ActionProposalInputActionsInnerAnyOf10Params
type ActionProposalInputActionsInnerAnyOf10Params struct {
	StagedAssetId        string         `json:"staged_asset_id" validate:"regexp=^stage_[a-f0-9]{40}$"`
	AssetType            string         `json:"asset_type"`
	Filename             string         `json:"filename"`
	ContentSha256        string         `json:"content_sha256" validate:"regexp=^[a-f0-9]{64}$"`
	MimeType             NullableString `json:"mime_type,omitempty"`
	SizeBytes            NullableInt32  `json:"size_bytes,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ActionProposalInputActionsInnerAnyOf10Params ActionProposalInputActionsInnerAnyOf10Params

// NewActionProposalInputActionsInnerAnyOf10Params instantiates a new ActionProposalInputActionsInnerAnyOf10Params object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActionProposalInputActionsInnerAnyOf10Params(stagedAssetId string, assetType string, filename string, contentSha256 string) *ActionProposalInputActionsInnerAnyOf10Params {
	this := ActionProposalInputActionsInnerAnyOf10Params{}
	this.StagedAssetId = stagedAssetId
	this.AssetType = assetType
	this.Filename = filename
	this.ContentSha256 = contentSha256
	return &this
}

// NewActionProposalInputActionsInnerAnyOf10ParamsWithDefaults instantiates a new ActionProposalInputActionsInnerAnyOf10Params object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActionProposalInputActionsInnerAnyOf10ParamsWithDefaults() *ActionProposalInputActionsInnerAnyOf10Params {
	this := ActionProposalInputActionsInnerAnyOf10Params{}
	return &this
}

// GetStagedAssetId returns the StagedAssetId field value
func (o *ActionProposalInputActionsInnerAnyOf10Params) GetStagedAssetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StagedAssetId
}

// GetStagedAssetIdOk returns a tuple with the StagedAssetId field value
// and a boolean to check if the value has been set.
func (o *ActionProposalInputActionsInnerAnyOf10Params) GetStagedAssetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StagedAssetId, true
}

// SetStagedAssetId sets field value
func (o *ActionProposalInputActionsInnerAnyOf10Params) SetStagedAssetId(v string) {
	o.StagedAssetId = v
}

// GetAssetType returns the AssetType field value
func (o *ActionProposalInputActionsInnerAnyOf10Params) GetAssetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetType
}

// GetAssetTypeOk returns a tuple with the AssetType field value
// and a boolean to check if the value has been set.
func (o *ActionProposalInputActionsInnerAnyOf10Params) GetAssetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetType, true
}

// SetAssetType sets field value
func (o *ActionProposalInputActionsInnerAnyOf10Params) SetAssetType(v string) {
	o.AssetType = v
}

// GetFilename returns the Filename field value
func (o *ActionProposalInputActionsInnerAnyOf10Params) GetFilename() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value
// and a boolean to check if the value has been set.
func (o *ActionProposalInputActionsInnerAnyOf10Params) GetFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filename, true
}

// SetFilename sets field value
func (o *ActionProposalInputActionsInnerAnyOf10Params) SetFilename(v string) {
	o.Filename = v
}

// GetContentSha256 returns the ContentSha256 field value
func (o *ActionProposalInputActionsInnerAnyOf10Params) GetContentSha256() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContentSha256
}

// GetContentSha256Ok returns a tuple with the ContentSha256 field value
// and a boolean to check if the value has been set.
func (o *ActionProposalInputActionsInnerAnyOf10Params) GetContentSha256Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentSha256, true
}

// SetContentSha256 sets field value
func (o *ActionProposalInputActionsInnerAnyOf10Params) SetContentSha256(v string) {
	o.ContentSha256 = v
}

// GetMimeType returns the MimeType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ActionProposalInputActionsInnerAnyOf10Params) GetMimeType() string {
	if o == nil || IsNil(o.MimeType.Get()) {
		var ret string
		return ret
	}
	return *o.MimeType.Get()
}

// GetMimeTypeOk returns a tuple with the MimeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ActionProposalInputActionsInnerAnyOf10Params) GetMimeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MimeType.Get(), o.MimeType.IsSet()
}

// HasMimeType returns a boolean if a field has been set.
func (o *ActionProposalInputActionsInnerAnyOf10Params) HasMimeType() bool {
	if o != nil && o.MimeType.IsSet() {
		return true
	}

	return false
}

// SetMimeType gets a reference to the given NullableString and assigns it to the MimeType field.
func (o *ActionProposalInputActionsInnerAnyOf10Params) SetMimeType(v string) {
	o.MimeType.Set(&v)
}

// SetMimeTypeNil sets the value for MimeType to be an explicit nil
func (o *ActionProposalInputActionsInnerAnyOf10Params) SetMimeTypeNil() {
	o.MimeType.Set(nil)
}

// UnsetMimeType ensures that no value is present for MimeType, not even an explicit nil
func (o *ActionProposalInputActionsInnerAnyOf10Params) UnsetMimeType() {
	o.MimeType.Unset()
}

// GetSizeBytes returns the SizeBytes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ActionProposalInputActionsInnerAnyOf10Params) GetSizeBytes() int32 {
	if o == nil || IsNil(o.SizeBytes.Get()) {
		var ret int32
		return ret
	}
	return *o.SizeBytes.Get()
}

// GetSizeBytesOk returns a tuple with the SizeBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ActionProposalInputActionsInnerAnyOf10Params) GetSizeBytesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SizeBytes.Get(), o.SizeBytes.IsSet()
}

// HasSizeBytes returns a boolean if a field has been set.
func (o *ActionProposalInputActionsInnerAnyOf10Params) HasSizeBytes() bool {
	if o != nil && o.SizeBytes.IsSet() {
		return true
	}

	return false
}

// SetSizeBytes gets a reference to the given NullableInt32 and assigns it to the SizeBytes field.
func (o *ActionProposalInputActionsInnerAnyOf10Params) SetSizeBytes(v int32) {
	o.SizeBytes.Set(&v)
}

// SetSizeBytesNil sets the value for SizeBytes to be an explicit nil
func (o *ActionProposalInputActionsInnerAnyOf10Params) SetSizeBytesNil() {
	o.SizeBytes.Set(nil)
}

// UnsetSizeBytes ensures that no value is present for SizeBytes, not even an explicit nil
func (o *ActionProposalInputActionsInnerAnyOf10Params) UnsetSizeBytes() {
	o.SizeBytes.Unset()
}

func (o ActionProposalInputActionsInnerAnyOf10Params) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActionProposalInputActionsInnerAnyOf10Params) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["staged_asset_id"] = o.StagedAssetId
	toSerialize["asset_type"] = o.AssetType
	toSerialize["filename"] = o.Filename
	toSerialize["content_sha256"] = o.ContentSha256
	if o.MimeType.IsSet() {
		toSerialize["mime_type"] = o.MimeType.Get()
	}
	if o.SizeBytes.IsSet() {
		toSerialize["size_bytes"] = o.SizeBytes.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ActionProposalInputActionsInnerAnyOf10Params) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"staged_asset_id",
		"asset_type",
		"filename",
		"content_sha256",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varActionProposalInputActionsInnerAnyOf10Params := _ActionProposalInputActionsInnerAnyOf10Params{}

	err = json.Unmarshal(data, &varActionProposalInputActionsInnerAnyOf10Params)

	if err != nil {
		return err
	}

	*o = ActionProposalInputActionsInnerAnyOf10Params(varActionProposalInputActionsInnerAnyOf10Params)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "staged_asset_id")
		delete(additionalProperties, "asset_type")
		delete(additionalProperties, "filename")
		delete(additionalProperties, "content_sha256")
		delete(additionalProperties, "mime_type")
		delete(additionalProperties, "size_bytes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableActionProposalInputActionsInnerAnyOf10Params struct {
	value *ActionProposalInputActionsInnerAnyOf10Params
	isSet bool
}

func (v NullableActionProposalInputActionsInnerAnyOf10Params) Get() *ActionProposalInputActionsInnerAnyOf10Params {
	return v.value
}

func (v *NullableActionProposalInputActionsInnerAnyOf10Params) Set(val *ActionProposalInputActionsInnerAnyOf10Params) {
	v.value = val
	v.isSet = true
}

func (v NullableActionProposalInputActionsInnerAnyOf10Params) IsSet() bool {
	return v.isSet
}

func (v *NullableActionProposalInputActionsInnerAnyOf10Params) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActionProposalInputActionsInnerAnyOf10Params(val *ActionProposalInputActionsInnerAnyOf10Params) *NullableActionProposalInputActionsInnerAnyOf10Params {
	return &NullableActionProposalInputActionsInnerAnyOf10Params{value: val, isSet: true}
}

func (v NullableActionProposalInputActionsInnerAnyOf10Params) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActionProposalInputActionsInnerAnyOf10Params) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
