/*
Plainrouter Conversion API

Plainrouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ValidateSandboxEventRequestValueData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidateSandboxEventRequestValueData{}

// ValidateSandboxEventRequestValueData Optional synthetic commerce data.
type ValidateSandboxEventRequestValueData struct {
	Value                *string `json:"value,omitempty"`
	Currency             *string `json:"currency,omitempty"`
	OrderId              *string `json:"order_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ValidateSandboxEventRequestValueData ValidateSandboxEventRequestValueData

// NewValidateSandboxEventRequestValueData instantiates a new ValidateSandboxEventRequestValueData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidateSandboxEventRequestValueData() *ValidateSandboxEventRequestValueData {
	this := ValidateSandboxEventRequestValueData{}
	return &this
}

// NewValidateSandboxEventRequestValueDataWithDefaults instantiates a new ValidateSandboxEventRequestValueData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidateSandboxEventRequestValueDataWithDefaults() *ValidateSandboxEventRequestValueData {
	this := ValidateSandboxEventRequestValueData{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ValidateSandboxEventRequestValueData) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidateSandboxEventRequestValueData) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ValidateSandboxEventRequestValueData) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *ValidateSandboxEventRequestValueData) SetValue(v string) {
	o.Value = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *ValidateSandboxEventRequestValueData) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidateSandboxEventRequestValueData) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *ValidateSandboxEventRequestValueData) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *ValidateSandboxEventRequestValueData) SetCurrency(v string) {
	o.Currency = &v
}

// GetOrderId returns the OrderId field value if set, zero value otherwise.
func (o *ValidateSandboxEventRequestValueData) GetOrderId() string {
	if o == nil || IsNil(o.OrderId) {
		var ret string
		return ret
	}
	return *o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidateSandboxEventRequestValueData) GetOrderIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrderId) {
		return nil, false
	}
	return o.OrderId, true
}

// HasOrderId returns a boolean if a field has been set.
func (o *ValidateSandboxEventRequestValueData) HasOrderId() bool {
	if o != nil && !IsNil(o.OrderId) {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given string and assigns it to the OrderId field.
func (o *ValidateSandboxEventRequestValueData) SetOrderId(v string) {
	o.OrderId = &v
}

func (o ValidateSandboxEventRequestValueData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidateSandboxEventRequestValueData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.OrderId) {
		toSerialize["order_id"] = o.OrderId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ValidateSandboxEventRequestValueData) UnmarshalJSON(data []byte) (err error) {
	varValidateSandboxEventRequestValueData := _ValidateSandboxEventRequestValueData{}

	err = json.Unmarshal(data, &varValidateSandboxEventRequestValueData)

	if err != nil {
		return err
	}

	*o = ValidateSandboxEventRequestValueData(varValidateSandboxEventRequestValueData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "value")
		delete(additionalProperties, "currency")
		delete(additionalProperties, "order_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableValidateSandboxEventRequestValueData struct {
	value *ValidateSandboxEventRequestValueData
	isSet bool
}

func (v NullableValidateSandboxEventRequestValueData) Get() *ValidateSandboxEventRequestValueData {
	return v.value
}

func (v *NullableValidateSandboxEventRequestValueData) Set(val *ValidateSandboxEventRequestValueData) {
	v.value = val
	v.isSet = true
}

func (v NullableValidateSandboxEventRequestValueData) IsSet() bool {
	return v.isSet
}

func (v *NullableValidateSandboxEventRequestValueData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidateSandboxEventRequestValueData(val *ValidateSandboxEventRequestValueData) *NullableValidateSandboxEventRequestValueData {
	return &NullableValidateSandboxEventRequestValueData{value: val, isSet: true}
}

func (v NullableValidateSandboxEventRequestValueData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidateSandboxEventRequestValueData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
