/*
PlainRouter Conversion API

PlainRouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ListEvents200ResponseEventsLinksInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListEvents200ResponseEventsLinksInner{}

// ListEvents200ResponseEventsLinksInner struct for ListEvents200ResponseEventsLinksInner
type ListEvents200ResponseEventsLinksInner struct {
	Url                  NullableString `json:"url"`
	Label                string         `json:"label"`
	Active               bool           `json:"active"`
	AdditionalProperties map[string]interface{}
}

type _ListEvents200ResponseEventsLinksInner ListEvents200ResponseEventsLinksInner

// NewListEvents200ResponseEventsLinksInner instantiates a new ListEvents200ResponseEventsLinksInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListEvents200ResponseEventsLinksInner(url NullableString, label string, active bool) *ListEvents200ResponseEventsLinksInner {
	this := ListEvents200ResponseEventsLinksInner{}
	this.Url = url
	this.Label = label
	this.Active = active
	return &this
}

// NewListEvents200ResponseEventsLinksInnerWithDefaults instantiates a new ListEvents200ResponseEventsLinksInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListEvents200ResponseEventsLinksInnerWithDefaults() *ListEvents200ResponseEventsLinksInner {
	this := ListEvents200ResponseEventsLinksInner{}
	return &this
}

// GetUrl returns the Url field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ListEvents200ResponseEventsLinksInner) GetUrl() string {
	if o == nil || o.Url.Get() == nil {
		var ret string
		return ret
	}

	return *o.Url.Get()
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListEvents200ResponseEventsLinksInner) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Url.Get(), o.Url.IsSet()
}

// SetUrl sets field value
func (o *ListEvents200ResponseEventsLinksInner) SetUrl(v string) {
	o.Url.Set(&v)
}

// GetLabel returns the Label field value
func (o *ListEvents200ResponseEventsLinksInner) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *ListEvents200ResponseEventsLinksInner) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *ListEvents200ResponseEventsLinksInner) SetLabel(v string) {
	o.Label = v
}

// GetActive returns the Active field value
func (o *ListEvents200ResponseEventsLinksInner) GetActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Active
}

// GetActiveOk returns a tuple with the Active field value
// and a boolean to check if the value has been set.
func (o *ListEvents200ResponseEventsLinksInner) GetActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Active, true
}

// SetActive sets field value
func (o *ListEvents200ResponseEventsLinksInner) SetActive(v bool) {
	o.Active = v
}

func (o ListEvents200ResponseEventsLinksInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListEvents200ResponseEventsLinksInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url.Get()
	toSerialize["label"] = o.Label
	toSerialize["active"] = o.Active

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListEvents200ResponseEventsLinksInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
		"label",
		"active",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListEvents200ResponseEventsLinksInner := _ListEvents200ResponseEventsLinksInner{}

	err = json.Unmarshal(data, &varListEvents200ResponseEventsLinksInner)

	if err != nil {
		return err
	}

	*o = ListEvents200ResponseEventsLinksInner(varListEvents200ResponseEventsLinksInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "url")
		delete(additionalProperties, "label")
		delete(additionalProperties, "active")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListEvents200ResponseEventsLinksInner struct {
	value *ListEvents200ResponseEventsLinksInner
	isSet bool
}

func (v NullableListEvents200ResponseEventsLinksInner) Get() *ListEvents200ResponseEventsLinksInner {
	return v.value
}

func (v *NullableListEvents200ResponseEventsLinksInner) Set(val *ListEvents200ResponseEventsLinksInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListEvents200ResponseEventsLinksInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListEvents200ResponseEventsLinksInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListEvents200ResponseEventsLinksInner(val *ListEvents200ResponseEventsLinksInner) *NullableListEvents200ResponseEventsLinksInner {
	return &NullableListEvents200ResponseEventsLinksInner{value: val, isSet: true}
}

func (v NullableListEvents200ResponseEventsLinksInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListEvents200ResponseEventsLinksInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
