/*
Plainrouter Conversion API

Plainrouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateEventRequestAnyOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateEventRequestAnyOf1{}

// CreateEventRequestAnyOf1 struct for CreateEventRequestAnyOf1
type CreateEventRequestAnyOf1 struct {
	// Caller-supplied idempotency key; maximum 128 characters.
	EventId *string `json:"event_id,omitempty"`
	// Signal event name; maximum 100 characters.
	EventName string `json:"event_name"`
	// Optional parent event id; maximum 128 characters.
	ParentEventId *string                           `json:"parent_event_id,omitempty"`
	EventTime     *CreateEventRequestAnyOfEventTime `json:"event_time,omitempty"`
	// Optional absolute source URL.
	EventSource *string `json:"event_source,omitempty"`
	// Optional action source; defaults to website and is limited to 50 characters.
	ActionSource *string `json:"action_source,omitempty"`
	// Optional visitor identifier; maximum 255 characters.
	VisitorId *string `json:"visitor_id,omitempty"`
	// Legal basis for processing. Legitimate-interest revenue lifecycle events are rejected; use an authenticated server adapter.
	ConsentBasis string `json:"consent_basis"`
	// Consent state supplied with the event.
	Consent map[string]*interface{} `json:"consent,omitempty"`
	// Consent Mode v2 signal values supplied with the event.
	ConsentMode map[string]*interface{} `json:"consent_mode,omitempty"`
	// TCF v2 data containing string and optional captured_at.
	Tcf map[string]*interface{} `json:"tcf,omitempty"`
	// Identity fields accepted by the tracker.
	UserData map[string]*interface{} `json:"user_data,omitempty"`
	// Advertising click identifiers.
	ClickIds             map[string]*interface{}           `json:"click_ids,omitempty"`
	ValueData            *CreateEventRequestAnyOfValueData `json:"value_data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateEventRequestAnyOf1 CreateEventRequestAnyOf1

// NewCreateEventRequestAnyOf1 instantiates a new CreateEventRequestAnyOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEventRequestAnyOf1(eventName string, consentBasis string) *CreateEventRequestAnyOf1 {
	this := CreateEventRequestAnyOf1{}
	this.EventName = eventName
	this.ConsentBasis = consentBasis
	return &this
}

// NewCreateEventRequestAnyOf1WithDefaults instantiates a new CreateEventRequestAnyOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEventRequestAnyOf1WithDefaults() *CreateEventRequestAnyOf1 {
	this := CreateEventRequestAnyOf1{}
	return &this
}

// GetEventId returns the EventId field value if set, zero value otherwise.
func (o *CreateEventRequestAnyOf1) GetEventId() string {
	if o == nil || IsNil(o.EventId) {
		var ret string
		return ret
	}
	return *o.EventId
}

// GetEventIdOk returns a tuple with the EventId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEventRequestAnyOf1) GetEventIdOk() (*string, bool) {
	if o == nil || IsNil(o.EventId) {
		return nil, false
	}
	return o.EventId, true
}

// HasEventId returns a boolean if a field has been set.
func (o *CreateEventRequestAnyOf1) HasEventId() bool {
	if o != nil && !IsNil(o.EventId) {
		return true
	}

	return false
}

// SetEventId gets a reference to the given string and assigns it to the EventId field.
func (o *CreateEventRequestAnyOf1) SetEventId(v string) {
	o.EventId = &v
}

// GetEventName returns the EventName field value
func (o *CreateEventRequestAnyOf1) GetEventName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventName
}

// GetEventNameOk returns a tuple with the EventName field value
// and a boolean to check if the value has been set.
func (o *CreateEventRequestAnyOf1) GetEventNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventName, true
}

// SetEventName sets field value
func (o *CreateEventRequestAnyOf1) SetEventName(v string) {
	o.EventName = v
}

// GetParentEventId returns the ParentEventId field value if set, zero value otherwise.
func (o *CreateEventRequestAnyOf1) GetParentEventId() string {
	if o == nil || IsNil(o.ParentEventId) {
		var ret string
		return ret
	}
	return *o.ParentEventId
}

// GetParentEventIdOk returns a tuple with the ParentEventId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEventRequestAnyOf1) GetParentEventIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParentEventId) {
		return nil, false
	}
	return o.ParentEventId, true
}

// HasParentEventId returns a boolean if a field has been set.
func (o *CreateEventRequestAnyOf1) HasParentEventId() bool {
	if o != nil && !IsNil(o.ParentEventId) {
		return true
	}

	return false
}

// SetParentEventId gets a reference to the given string and assigns it to the ParentEventId field.
func (o *CreateEventRequestAnyOf1) SetParentEventId(v string) {
	o.ParentEventId = &v
}

// GetEventTime returns the EventTime field value if set, zero value otherwise.
func (o *CreateEventRequestAnyOf1) GetEventTime() CreateEventRequestAnyOfEventTime {
	if o == nil || IsNil(o.EventTime) {
		var ret CreateEventRequestAnyOfEventTime
		return ret
	}
	return *o.EventTime
}

// GetEventTimeOk returns a tuple with the EventTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEventRequestAnyOf1) GetEventTimeOk() (*CreateEventRequestAnyOfEventTime, bool) {
	if o == nil || IsNil(o.EventTime) {
		return nil, false
	}
	return o.EventTime, true
}

// HasEventTime returns a boolean if a field has been set.
func (o *CreateEventRequestAnyOf1) HasEventTime() bool {
	if o != nil && !IsNil(o.EventTime) {
		return true
	}

	return false
}

// SetEventTime gets a reference to the given CreateEventRequestAnyOfEventTime and assigns it to the EventTime field.
func (o *CreateEventRequestAnyOf1) SetEventTime(v CreateEventRequestAnyOfEventTime) {
	o.EventTime = &v
}

// GetEventSource returns the EventSource field value if set, zero value otherwise.
func (o *CreateEventRequestAnyOf1) GetEventSource() string {
	if o == nil || IsNil(o.EventSource) {
		var ret string
		return ret
	}
	return *o.EventSource
}

// GetEventSourceOk returns a tuple with the EventSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEventRequestAnyOf1) GetEventSourceOk() (*string, bool) {
	if o == nil || IsNil(o.EventSource) {
		return nil, false
	}
	return o.EventSource, true
}

// HasEventSource returns a boolean if a field has been set.
func (o *CreateEventRequestAnyOf1) HasEventSource() bool {
	if o != nil && !IsNil(o.EventSource) {
		return true
	}

	return false
}

// SetEventSource gets a reference to the given string and assigns it to the EventSource field.
func (o *CreateEventRequestAnyOf1) SetEventSource(v string) {
	o.EventSource = &v
}

// GetActionSource returns the ActionSource field value if set, zero value otherwise.
func (o *CreateEventRequestAnyOf1) GetActionSource() string {
	if o == nil || IsNil(o.ActionSource) {
		var ret string
		return ret
	}
	return *o.ActionSource
}

// GetActionSourceOk returns a tuple with the ActionSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEventRequestAnyOf1) GetActionSourceOk() (*string, bool) {
	if o == nil || IsNil(o.ActionSource) {
		return nil, false
	}
	return o.ActionSource, true
}

// HasActionSource returns a boolean if a field has been set.
func (o *CreateEventRequestAnyOf1) HasActionSource() bool {
	if o != nil && !IsNil(o.ActionSource) {
		return true
	}

	return false
}

// SetActionSource gets a reference to the given string and assigns it to the ActionSource field.
func (o *CreateEventRequestAnyOf1) SetActionSource(v string) {
	o.ActionSource = &v
}

// GetVisitorId returns the VisitorId field value if set, zero value otherwise.
func (o *CreateEventRequestAnyOf1) GetVisitorId() string {
	if o == nil || IsNil(o.VisitorId) {
		var ret string
		return ret
	}
	return *o.VisitorId
}

// GetVisitorIdOk returns a tuple with the VisitorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEventRequestAnyOf1) GetVisitorIdOk() (*string, bool) {
	if o == nil || IsNil(o.VisitorId) {
		return nil, false
	}
	return o.VisitorId, true
}

// HasVisitorId returns a boolean if a field has been set.
func (o *CreateEventRequestAnyOf1) HasVisitorId() bool {
	if o != nil && !IsNil(o.VisitorId) {
		return true
	}

	return false
}

// SetVisitorId gets a reference to the given string and assigns it to the VisitorId field.
func (o *CreateEventRequestAnyOf1) SetVisitorId(v string) {
	o.VisitorId = &v
}

// GetConsentBasis returns the ConsentBasis field value
func (o *CreateEventRequestAnyOf1) GetConsentBasis() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConsentBasis
}

// GetConsentBasisOk returns a tuple with the ConsentBasis field value
// and a boolean to check if the value has been set.
func (o *CreateEventRequestAnyOf1) GetConsentBasisOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConsentBasis, true
}

// SetConsentBasis sets field value
func (o *CreateEventRequestAnyOf1) SetConsentBasis(v string) {
	o.ConsentBasis = v
}

// GetConsent returns the Consent field value if set, zero value otherwise.
func (o *CreateEventRequestAnyOf1) GetConsent() map[string]*interface{} {
	if o == nil || IsNil(o.Consent) {
		var ret map[string]*interface{}
		return ret
	}
	return o.Consent
}

// GetConsentOk returns a tuple with the Consent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEventRequestAnyOf1) GetConsentOk() (map[string]*interface{}, bool) {
	if o == nil || IsNil(o.Consent) {
		return map[string]*interface{}{}, false
	}
	return o.Consent, true
}

// HasConsent returns a boolean if a field has been set.
func (o *CreateEventRequestAnyOf1) HasConsent() bool {
	if o != nil && !IsNil(o.Consent) {
		return true
	}

	return false
}

// SetConsent gets a reference to the given map[string]*interface{} and assigns it to the Consent field.
func (o *CreateEventRequestAnyOf1) SetConsent(v map[string]*interface{}) {
	o.Consent = v
}

// GetConsentMode returns the ConsentMode field value if set, zero value otherwise.
func (o *CreateEventRequestAnyOf1) GetConsentMode() map[string]*interface{} {
	if o == nil || IsNil(o.ConsentMode) {
		var ret map[string]*interface{}
		return ret
	}
	return o.ConsentMode
}

// GetConsentModeOk returns a tuple with the ConsentMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEventRequestAnyOf1) GetConsentModeOk() (map[string]*interface{}, bool) {
	if o == nil || IsNil(o.ConsentMode) {
		return map[string]*interface{}{}, false
	}
	return o.ConsentMode, true
}

// HasConsentMode returns a boolean if a field has been set.
func (o *CreateEventRequestAnyOf1) HasConsentMode() bool {
	if o != nil && !IsNil(o.ConsentMode) {
		return true
	}

	return false
}

// SetConsentMode gets a reference to the given map[string]*interface{} and assigns it to the ConsentMode field.
func (o *CreateEventRequestAnyOf1) SetConsentMode(v map[string]*interface{}) {
	o.ConsentMode = v
}

// GetTcf returns the Tcf field value if set, zero value otherwise.
func (o *CreateEventRequestAnyOf1) GetTcf() map[string]*interface{} {
	if o == nil || IsNil(o.Tcf) {
		var ret map[string]*interface{}
		return ret
	}
	return o.Tcf
}

// GetTcfOk returns a tuple with the Tcf field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEventRequestAnyOf1) GetTcfOk() (map[string]*interface{}, bool) {
	if o == nil || IsNil(o.Tcf) {
		return map[string]*interface{}{}, false
	}
	return o.Tcf, true
}

// HasTcf returns a boolean if a field has been set.
func (o *CreateEventRequestAnyOf1) HasTcf() bool {
	if o != nil && !IsNil(o.Tcf) {
		return true
	}

	return false
}

// SetTcf gets a reference to the given map[string]*interface{} and assigns it to the Tcf field.
func (o *CreateEventRequestAnyOf1) SetTcf(v map[string]*interface{}) {
	o.Tcf = v
}

// GetUserData returns the UserData field value if set, zero value otherwise.
func (o *CreateEventRequestAnyOf1) GetUserData() map[string]*interface{} {
	if o == nil || IsNil(o.UserData) {
		var ret map[string]*interface{}
		return ret
	}
	return o.UserData
}

// GetUserDataOk returns a tuple with the UserData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEventRequestAnyOf1) GetUserDataOk() (map[string]*interface{}, bool) {
	if o == nil || IsNil(o.UserData) {
		return map[string]*interface{}{}, false
	}
	return o.UserData, true
}

// HasUserData returns a boolean if a field has been set.
func (o *CreateEventRequestAnyOf1) HasUserData() bool {
	if o != nil && !IsNil(o.UserData) {
		return true
	}

	return false
}

// SetUserData gets a reference to the given map[string]*interface{} and assigns it to the UserData field.
func (o *CreateEventRequestAnyOf1) SetUserData(v map[string]*interface{}) {
	o.UserData = v
}

// GetClickIds returns the ClickIds field value if set, zero value otherwise.
func (o *CreateEventRequestAnyOf1) GetClickIds() map[string]*interface{} {
	if o == nil || IsNil(o.ClickIds) {
		var ret map[string]*interface{}
		return ret
	}
	return o.ClickIds
}

// GetClickIdsOk returns a tuple with the ClickIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEventRequestAnyOf1) GetClickIdsOk() (map[string]*interface{}, bool) {
	if o == nil || IsNil(o.ClickIds) {
		return map[string]*interface{}{}, false
	}
	return o.ClickIds, true
}

// HasClickIds returns a boolean if a field has been set.
func (o *CreateEventRequestAnyOf1) HasClickIds() bool {
	if o != nil && !IsNil(o.ClickIds) {
		return true
	}

	return false
}

// SetClickIds gets a reference to the given map[string]*interface{} and assigns it to the ClickIds field.
func (o *CreateEventRequestAnyOf1) SetClickIds(v map[string]*interface{}) {
	o.ClickIds = v
}

// GetValueData returns the ValueData field value if set, zero value otherwise.
func (o *CreateEventRequestAnyOf1) GetValueData() CreateEventRequestAnyOfValueData {
	if o == nil || IsNil(o.ValueData) {
		var ret CreateEventRequestAnyOfValueData
		return ret
	}
	return *o.ValueData
}

// GetValueDataOk returns a tuple with the ValueData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEventRequestAnyOf1) GetValueDataOk() (*CreateEventRequestAnyOfValueData, bool) {
	if o == nil || IsNil(o.ValueData) {
		return nil, false
	}
	return o.ValueData, true
}

// HasValueData returns a boolean if a field has been set.
func (o *CreateEventRequestAnyOf1) HasValueData() bool {
	if o != nil && !IsNil(o.ValueData) {
		return true
	}

	return false
}

// SetValueData gets a reference to the given CreateEventRequestAnyOfValueData and assigns it to the ValueData field.
func (o *CreateEventRequestAnyOf1) SetValueData(v CreateEventRequestAnyOfValueData) {
	o.ValueData = &v
}

func (o CreateEventRequestAnyOf1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateEventRequestAnyOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EventId) {
		toSerialize["event_id"] = o.EventId
	}
	toSerialize["event_name"] = o.EventName
	if !IsNil(o.ParentEventId) {
		toSerialize["parent_event_id"] = o.ParentEventId
	}
	if !IsNil(o.EventTime) {
		toSerialize["event_time"] = o.EventTime
	}
	if !IsNil(o.EventSource) {
		toSerialize["event_source"] = o.EventSource
	}
	if !IsNil(o.ActionSource) {
		toSerialize["action_source"] = o.ActionSource
	}
	if !IsNil(o.VisitorId) {
		toSerialize["visitor_id"] = o.VisitorId
	}
	toSerialize["consent_basis"] = o.ConsentBasis
	if !IsNil(o.Consent) {
		toSerialize["consent"] = o.Consent
	}
	if !IsNil(o.ConsentMode) {
		toSerialize["consent_mode"] = o.ConsentMode
	}
	if !IsNil(o.Tcf) {
		toSerialize["tcf"] = o.Tcf
	}
	if !IsNil(o.UserData) {
		toSerialize["user_data"] = o.UserData
	}
	if !IsNil(o.ClickIds) {
		toSerialize["click_ids"] = o.ClickIds
	}
	if !IsNil(o.ValueData) {
		toSerialize["value_data"] = o.ValueData
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateEventRequestAnyOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event_name",
		"consent_basis",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateEventRequestAnyOf1 := _CreateEventRequestAnyOf1{}

	err = json.Unmarshal(data, &varCreateEventRequestAnyOf1)

	if err != nil {
		return err
	}

	*o = CreateEventRequestAnyOf1(varCreateEventRequestAnyOf1)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "event_id")
		delete(additionalProperties, "event_name")
		delete(additionalProperties, "parent_event_id")
		delete(additionalProperties, "event_time")
		delete(additionalProperties, "event_source")
		delete(additionalProperties, "action_source")
		delete(additionalProperties, "visitor_id")
		delete(additionalProperties, "consent_basis")
		delete(additionalProperties, "consent")
		delete(additionalProperties, "consent_mode")
		delete(additionalProperties, "tcf")
		delete(additionalProperties, "user_data")
		delete(additionalProperties, "click_ids")
		delete(additionalProperties, "value_data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateEventRequestAnyOf1 struct {
	value *CreateEventRequestAnyOf1
	isSet bool
}

func (v NullableCreateEventRequestAnyOf1) Get() *CreateEventRequestAnyOf1 {
	return v.value
}

func (v *NullableCreateEventRequestAnyOf1) Set(val *CreateEventRequestAnyOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEventRequestAnyOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEventRequestAnyOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEventRequestAnyOf1(val *CreateEventRequestAnyOf1) *NullableCreateEventRequestAnyOf1 {
	return &NullableCreateEventRequestAnyOf1{value: val, isSet: true}
}

func (v NullableCreateEventRequestAnyOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEventRequestAnyOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
