/*
Plainrouter Conversion API

Plainrouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ActionReadItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActionReadItem{}

// ActionReadItem struct for ActionReadItem
type ActionReadItem struct {
	Id                   string                   `json:"id"`
	BatchId              string                   `json:"batch_id"`
	WorkspaceId          int32                    `json:"workspace_id"`
	Type                 string                   `json:"type"`
	TargetEntityType     string                   `json:"target_entity_type"`
	TargetEntityId       string                   `json:"target_entity_id"`
	TargetEntityName     NullableString           `json:"target_entity_name"`
	Params               interface{}              `json:"params"`
	Rationale            string                   `json:"rationale"`
	Status               string                   `json:"status"`
	BatchStatus          string                   `json:"batch_status"`
	Disposition          ActionCurrentDisposition `json:"disposition"`
	PolicyDecision       NullableString           `json:"policy_decision"`
	PolicyReasons        []string                 `json:"policy_reasons"`
	AdditionalProperties map[string]interface{}
}

type _ActionReadItem ActionReadItem

// NewActionReadItem instantiates a new ActionReadItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActionReadItem(id string, batchId string, workspaceId int32, type_ string, targetEntityType string, targetEntityId string, targetEntityName NullableString, params interface{}, rationale string, status string, batchStatus string, disposition ActionCurrentDisposition, policyDecision NullableString, policyReasons []string) *ActionReadItem {
	this := ActionReadItem{}
	this.Id = id
	this.BatchId = batchId
	this.WorkspaceId = workspaceId
	this.Type = type_
	this.TargetEntityType = targetEntityType
	this.TargetEntityId = targetEntityId
	this.TargetEntityName = targetEntityName
	this.Params = params
	this.Rationale = rationale
	this.Status = status
	this.BatchStatus = batchStatus
	this.Disposition = disposition
	this.PolicyDecision = policyDecision
	this.PolicyReasons = policyReasons
	return &this
}

// NewActionReadItemWithDefaults instantiates a new ActionReadItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActionReadItemWithDefaults() *ActionReadItem {
	this := ActionReadItem{}
	return &this
}

// GetId returns the Id field value
func (o *ActionReadItem) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ActionReadItem) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ActionReadItem) SetId(v string) {
	o.Id = v
}

// GetBatchId returns the BatchId field value
func (o *ActionReadItem) GetBatchId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BatchId
}

// GetBatchIdOk returns a tuple with the BatchId field value
// and a boolean to check if the value has been set.
func (o *ActionReadItem) GetBatchIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BatchId, true
}

// SetBatchId sets field value
func (o *ActionReadItem) SetBatchId(v string) {
	o.BatchId = v
}

// GetWorkspaceId returns the WorkspaceId field value
func (o *ActionReadItem) GetWorkspaceId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WorkspaceId
}

// GetWorkspaceIdOk returns a tuple with the WorkspaceId field value
// and a boolean to check if the value has been set.
func (o *ActionReadItem) GetWorkspaceIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkspaceId, true
}

// SetWorkspaceId sets field value
func (o *ActionReadItem) SetWorkspaceId(v int32) {
	o.WorkspaceId = v
}

// GetType returns the Type field value
func (o *ActionReadItem) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ActionReadItem) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ActionReadItem) SetType(v string) {
	o.Type = v
}

// GetTargetEntityType returns the TargetEntityType field value
func (o *ActionReadItem) GetTargetEntityType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetEntityType
}

// GetTargetEntityTypeOk returns a tuple with the TargetEntityType field value
// and a boolean to check if the value has been set.
func (o *ActionReadItem) GetTargetEntityTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetEntityType, true
}

// SetTargetEntityType sets field value
func (o *ActionReadItem) SetTargetEntityType(v string) {
	o.TargetEntityType = v
}

// GetTargetEntityId returns the TargetEntityId field value
func (o *ActionReadItem) GetTargetEntityId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetEntityId
}

// GetTargetEntityIdOk returns a tuple with the TargetEntityId field value
// and a boolean to check if the value has been set.
func (o *ActionReadItem) GetTargetEntityIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetEntityId, true
}

// SetTargetEntityId sets field value
func (o *ActionReadItem) SetTargetEntityId(v string) {
	o.TargetEntityId = v
}

// GetTargetEntityName returns the TargetEntityName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ActionReadItem) GetTargetEntityName() string {
	if o == nil || o.TargetEntityName.Get() == nil {
		var ret string
		return ret
	}

	return *o.TargetEntityName.Get()
}

// GetTargetEntityNameOk returns a tuple with the TargetEntityName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ActionReadItem) GetTargetEntityNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TargetEntityName.Get(), o.TargetEntityName.IsSet()
}

// SetTargetEntityName sets field value
func (o *ActionReadItem) SetTargetEntityName(v string) {
	o.TargetEntityName.Set(&v)
}

// GetParams returns the Params field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ActionReadItem) GetParams() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Params
}

// GetParamsOk returns a tuple with the Params field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ActionReadItem) GetParamsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Params) {
		return nil, false
	}
	return &o.Params, true
}

// SetParams sets field value
func (o *ActionReadItem) SetParams(v interface{}) {
	o.Params = v
}

// GetRationale returns the Rationale field value
func (o *ActionReadItem) GetRationale() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Rationale
}

// GetRationaleOk returns a tuple with the Rationale field value
// and a boolean to check if the value has been set.
func (o *ActionReadItem) GetRationaleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rationale, true
}

// SetRationale sets field value
func (o *ActionReadItem) SetRationale(v string) {
	o.Rationale = v
}

// GetStatus returns the Status field value
func (o *ActionReadItem) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ActionReadItem) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ActionReadItem) SetStatus(v string) {
	o.Status = v
}

// GetBatchStatus returns the BatchStatus field value
func (o *ActionReadItem) GetBatchStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BatchStatus
}

// GetBatchStatusOk returns a tuple with the BatchStatus field value
// and a boolean to check if the value has been set.
func (o *ActionReadItem) GetBatchStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BatchStatus, true
}

// SetBatchStatus sets field value
func (o *ActionReadItem) SetBatchStatus(v string) {
	o.BatchStatus = v
}

// GetDisposition returns the Disposition field value
func (o *ActionReadItem) GetDisposition() ActionCurrentDisposition {
	if o == nil {
		var ret ActionCurrentDisposition
		return ret
	}

	return o.Disposition
}

// GetDispositionOk returns a tuple with the Disposition field value
// and a boolean to check if the value has been set.
func (o *ActionReadItem) GetDispositionOk() (*ActionCurrentDisposition, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Disposition, true
}

// SetDisposition sets field value
func (o *ActionReadItem) SetDisposition(v ActionCurrentDisposition) {
	o.Disposition = v
}

// GetPolicyDecision returns the PolicyDecision field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ActionReadItem) GetPolicyDecision() string {
	if o == nil || o.PolicyDecision.Get() == nil {
		var ret string
		return ret
	}

	return *o.PolicyDecision.Get()
}

// GetPolicyDecisionOk returns a tuple with the PolicyDecision field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ActionReadItem) GetPolicyDecisionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PolicyDecision.Get(), o.PolicyDecision.IsSet()
}

// SetPolicyDecision sets field value
func (o *ActionReadItem) SetPolicyDecision(v string) {
	o.PolicyDecision.Set(&v)
}

// GetPolicyReasons returns the PolicyReasons field value
func (o *ActionReadItem) GetPolicyReasons() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.PolicyReasons
}

// GetPolicyReasonsOk returns a tuple with the PolicyReasons field value
// and a boolean to check if the value has been set.
func (o *ActionReadItem) GetPolicyReasonsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PolicyReasons, true
}

// SetPolicyReasons sets field value
func (o *ActionReadItem) SetPolicyReasons(v []string) {
	o.PolicyReasons = v
}

func (o ActionReadItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActionReadItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["batch_id"] = o.BatchId
	toSerialize["workspace_id"] = o.WorkspaceId
	toSerialize["type"] = o.Type
	toSerialize["target_entity_type"] = o.TargetEntityType
	toSerialize["target_entity_id"] = o.TargetEntityId
	toSerialize["target_entity_name"] = o.TargetEntityName.Get()
	if o.Params != nil {
		toSerialize["params"] = o.Params
	}
	toSerialize["rationale"] = o.Rationale
	toSerialize["status"] = o.Status
	toSerialize["batch_status"] = o.BatchStatus
	toSerialize["disposition"] = o.Disposition
	toSerialize["policy_decision"] = o.PolicyDecision.Get()
	toSerialize["policy_reasons"] = o.PolicyReasons

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ActionReadItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"batch_id",
		"workspace_id",
		"type",
		"target_entity_type",
		"target_entity_id",
		"target_entity_name",
		"params",
		"rationale",
		"status",
		"batch_status",
		"disposition",
		"policy_decision",
		"policy_reasons",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varActionReadItem := _ActionReadItem{}

	err = json.Unmarshal(data, &varActionReadItem)

	if err != nil {
		return err
	}

	*o = ActionReadItem(varActionReadItem)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "batch_id")
		delete(additionalProperties, "workspace_id")
		delete(additionalProperties, "type")
		delete(additionalProperties, "target_entity_type")
		delete(additionalProperties, "target_entity_id")
		delete(additionalProperties, "target_entity_name")
		delete(additionalProperties, "params")
		delete(additionalProperties, "rationale")
		delete(additionalProperties, "status")
		delete(additionalProperties, "batch_status")
		delete(additionalProperties, "disposition")
		delete(additionalProperties, "policy_decision")
		delete(additionalProperties, "policy_reasons")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableActionReadItem struct {
	value *ActionReadItem
	isSet bool
}

func (v NullableActionReadItem) Get() *ActionReadItem {
	return v.value
}

func (v *NullableActionReadItem) Set(val *ActionReadItem) {
	v.value = val
	v.isSet = true
}

func (v NullableActionReadItem) IsSet() bool {
	return v.isSet
}

func (v *NullableActionReadItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActionReadItem(val *ActionReadItem) *NullableActionReadItem {
	return &NullableActionReadItem{value: val, isSet: true}
}

func (v NullableActionReadItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActionReadItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
