/*
PlainRouter Conversion API

PlainRouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GetEvent200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEvent200Response{}

// GetEvent200Response struct for GetEvent200Response
type GetEvent200Response struct {
	Event                GetEvent200ResponseEvent             `json:"event"`
	Lineage              GetEvent200ResponseLineage           `json:"lineage"`
	Deliveries           []GetEvent200ResponseDeliveriesInner `json:"deliveries"`
	AdditionalProperties map[string]interface{}
}

type _GetEvent200Response GetEvent200Response

// NewGetEvent200Response instantiates a new GetEvent200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEvent200Response(event GetEvent200ResponseEvent, lineage GetEvent200ResponseLineage, deliveries []GetEvent200ResponseDeliveriesInner) *GetEvent200Response {
	this := GetEvent200Response{}
	this.Event = event
	this.Lineage = lineage
	this.Deliveries = deliveries
	return &this
}

// NewGetEvent200ResponseWithDefaults instantiates a new GetEvent200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEvent200ResponseWithDefaults() *GetEvent200Response {
	this := GetEvent200Response{}
	return &this
}

// GetEvent returns the Event field value
func (o *GetEvent200Response) GetEvent() GetEvent200ResponseEvent {
	if o == nil {
		var ret GetEvent200ResponseEvent
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *GetEvent200Response) GetEventOk() (*GetEvent200ResponseEvent, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *GetEvent200Response) SetEvent(v GetEvent200ResponseEvent) {
	o.Event = v
}

// GetLineage returns the Lineage field value
func (o *GetEvent200Response) GetLineage() GetEvent200ResponseLineage {
	if o == nil {
		var ret GetEvent200ResponseLineage
		return ret
	}

	return o.Lineage
}

// GetLineageOk returns a tuple with the Lineage field value
// and a boolean to check if the value has been set.
func (o *GetEvent200Response) GetLineageOk() (*GetEvent200ResponseLineage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Lineage, true
}

// SetLineage sets field value
func (o *GetEvent200Response) SetLineage(v GetEvent200ResponseLineage) {
	o.Lineage = v
}

// GetDeliveries returns the Deliveries field value
func (o *GetEvent200Response) GetDeliveries() []GetEvent200ResponseDeliveriesInner {
	if o == nil {
		var ret []GetEvent200ResponseDeliveriesInner
		return ret
	}

	return o.Deliveries
}

// GetDeliveriesOk returns a tuple with the Deliveries field value
// and a boolean to check if the value has been set.
func (o *GetEvent200Response) GetDeliveriesOk() ([]GetEvent200ResponseDeliveriesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Deliveries, true
}

// SetDeliveries sets field value
func (o *GetEvent200Response) SetDeliveries(v []GetEvent200ResponseDeliveriesInner) {
	o.Deliveries = v
}

func (o GetEvent200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEvent200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event"] = o.Event
	toSerialize["lineage"] = o.Lineage
	toSerialize["deliveries"] = o.Deliveries

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetEvent200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event",
		"lineage",
		"deliveries",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetEvent200Response := _GetEvent200Response{}

	err = json.Unmarshal(data, &varGetEvent200Response)

	if err != nil {
		return err
	}

	*o = GetEvent200Response(varGetEvent200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "event")
		delete(additionalProperties, "lineage")
		delete(additionalProperties, "deliveries")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetEvent200Response struct {
	value *GetEvent200Response
	isSet bool
}

func (v NullableGetEvent200Response) Get() *GetEvent200Response {
	return v.value
}

func (v *NullableGetEvent200Response) Set(val *GetEvent200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEvent200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEvent200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEvent200Response(val *GetEvent200Response) *NullableGetEvent200Response {
	return &NullableGetEvent200Response{value: val, isSet: true}
}

func (v NullableGetEvent200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEvent200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
