/*
PlainRouter Conversion API

PlainRouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ListEventsByCursor200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListEventsByCursor200Response{}

// ListEventsByCursor200Response struct for ListEventsByCursor200Response
type ListEventsByCursor200Response struct {
	Events               ListEventsByCursor200ResponseEvents `json:"events"`
	Metrics              ListEvents200ResponseMetrics        `json:"metrics"`
	AdditionalProperties map[string]interface{}
}

type _ListEventsByCursor200Response ListEventsByCursor200Response

// NewListEventsByCursor200Response instantiates a new ListEventsByCursor200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListEventsByCursor200Response(events ListEventsByCursor200ResponseEvents, metrics ListEvents200ResponseMetrics) *ListEventsByCursor200Response {
	this := ListEventsByCursor200Response{}
	this.Events = events
	this.Metrics = metrics
	return &this
}

// NewListEventsByCursor200ResponseWithDefaults instantiates a new ListEventsByCursor200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListEventsByCursor200ResponseWithDefaults() *ListEventsByCursor200Response {
	this := ListEventsByCursor200Response{}
	return &this
}

// GetEvents returns the Events field value
func (o *ListEventsByCursor200Response) GetEvents() ListEventsByCursor200ResponseEvents {
	if o == nil {
		var ret ListEventsByCursor200ResponseEvents
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *ListEventsByCursor200Response) GetEventsOk() (*ListEventsByCursor200ResponseEvents, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Events, true
}

// SetEvents sets field value
func (o *ListEventsByCursor200Response) SetEvents(v ListEventsByCursor200ResponseEvents) {
	o.Events = v
}

// GetMetrics returns the Metrics field value
func (o *ListEventsByCursor200Response) GetMetrics() ListEvents200ResponseMetrics {
	if o == nil {
		var ret ListEvents200ResponseMetrics
		return ret
	}

	return o.Metrics
}

// GetMetricsOk returns a tuple with the Metrics field value
// and a boolean to check if the value has been set.
func (o *ListEventsByCursor200Response) GetMetricsOk() (*ListEvents200ResponseMetrics, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metrics, true
}

// SetMetrics sets field value
func (o *ListEventsByCursor200Response) SetMetrics(v ListEvents200ResponseMetrics) {
	o.Metrics = v
}

func (o ListEventsByCursor200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListEventsByCursor200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["events"] = o.Events
	toSerialize["metrics"] = o.Metrics

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListEventsByCursor200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"events",
		"metrics",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListEventsByCursor200Response := _ListEventsByCursor200Response{}

	err = json.Unmarshal(data, &varListEventsByCursor200Response)

	if err != nil {
		return err
	}

	*o = ListEventsByCursor200Response(varListEventsByCursor200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "events")
		delete(additionalProperties, "metrics")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListEventsByCursor200Response struct {
	value *ListEventsByCursor200Response
	isSet bool
}

func (v NullableListEventsByCursor200Response) Get() *ListEventsByCursor200Response {
	return v.value
}

func (v *NullableListEventsByCursor200Response) Set(val *ListEventsByCursor200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListEventsByCursor200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListEventsByCursor200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListEventsByCursor200Response(val *ListEventsByCursor200Response) *NullableListEventsByCursor200Response {
	return &NullableListEventsByCursor200Response{value: val, isSet: true}
}

func (v NullableListEventsByCursor200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListEventsByCursor200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
