/*
PlainRouter Conversion API

PlainRouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateEvent200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateEvent200Response{}

// CreateEvent200Response struct for CreateEvent200Response
type CreateEvent200Response struct {
	EventId              string `json:"event_id"`
	Duplicate            bool   `json:"duplicate"`
	AdditionalProperties map[string]interface{}
}

type _CreateEvent200Response CreateEvent200Response

// NewCreateEvent200Response instantiates a new CreateEvent200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEvent200Response(eventId string, duplicate bool) *CreateEvent200Response {
	this := CreateEvent200Response{}
	this.EventId = eventId
	this.Duplicate = duplicate
	return &this
}

// NewCreateEvent200ResponseWithDefaults instantiates a new CreateEvent200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEvent200ResponseWithDefaults() *CreateEvent200Response {
	this := CreateEvent200Response{}
	return &this
}

// GetEventId returns the EventId field value
func (o *CreateEvent200Response) GetEventId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventId
}

// GetEventIdOk returns a tuple with the EventId field value
// and a boolean to check if the value has been set.
func (o *CreateEvent200Response) GetEventIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventId, true
}

// SetEventId sets field value
func (o *CreateEvent200Response) SetEventId(v string) {
	o.EventId = v
}

// GetDuplicate returns the Duplicate field value
func (o *CreateEvent200Response) GetDuplicate() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Duplicate
}

// GetDuplicateOk returns a tuple with the Duplicate field value
// and a boolean to check if the value has been set.
func (o *CreateEvent200Response) GetDuplicateOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Duplicate, true
}

// SetDuplicate sets field value
func (o *CreateEvent200Response) SetDuplicate(v bool) {
	o.Duplicate = v
}

func (o CreateEvent200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateEvent200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event_id"] = o.EventId
	toSerialize["duplicate"] = o.Duplicate

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateEvent200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event_id",
		"duplicate",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateEvent200Response := _CreateEvent200Response{}

	err = json.Unmarshal(data, &varCreateEvent200Response)

	if err != nil {
		return err
	}

	*o = CreateEvent200Response(varCreateEvent200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "event_id")
		delete(additionalProperties, "duplicate")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateEvent200Response struct {
	value *CreateEvent200Response
	isSet bool
}

func (v NullableCreateEvent200Response) Get() *CreateEvent200Response {
	return v.value
}

func (v *NullableCreateEvent200Response) Set(val *CreateEvent200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEvent200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEvent200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEvent200Response(val *CreateEvent200Response) *NullableCreateEvent200Response {
	return &NullableCreateEvent200Response{value: val, isSet: true}
}

func (v NullableCreateEvent200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEvent200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
