/*
Plainrouter Conversion API

Plainrouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ActionProposalInputEvidenceInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActionProposalInputEvidenceInner{}

// ActionProposalInputEvidenceInner struct for ActionProposalInputEvidenceInner
type ActionProposalInputEvidenceInner struct {
	SourceTool  string   `json:"source_tool"`
	FieldsUsed  []string `json:"fields_used"`
	ActionIndex *int32   `json:"action_index,omitempty"`
}

type _ActionProposalInputEvidenceInner ActionProposalInputEvidenceInner

// NewActionProposalInputEvidenceInner instantiates a new ActionProposalInputEvidenceInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActionProposalInputEvidenceInner(sourceTool string, fieldsUsed []string) *ActionProposalInputEvidenceInner {
	this := ActionProposalInputEvidenceInner{}
	this.SourceTool = sourceTool
	this.FieldsUsed = fieldsUsed
	return &this
}

// NewActionProposalInputEvidenceInnerWithDefaults instantiates a new ActionProposalInputEvidenceInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActionProposalInputEvidenceInnerWithDefaults() *ActionProposalInputEvidenceInner {
	this := ActionProposalInputEvidenceInner{}
	return &this
}

// GetSourceTool returns the SourceTool field value
func (o *ActionProposalInputEvidenceInner) GetSourceTool() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceTool
}

// GetSourceToolOk returns a tuple with the SourceTool field value
// and a boolean to check if the value has been set.
func (o *ActionProposalInputEvidenceInner) GetSourceToolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceTool, true
}

// SetSourceTool sets field value
func (o *ActionProposalInputEvidenceInner) SetSourceTool(v string) {
	o.SourceTool = v
}

// GetFieldsUsed returns the FieldsUsed field value
func (o *ActionProposalInputEvidenceInner) GetFieldsUsed() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.FieldsUsed
}

// GetFieldsUsedOk returns a tuple with the FieldsUsed field value
// and a boolean to check if the value has been set.
func (o *ActionProposalInputEvidenceInner) GetFieldsUsedOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FieldsUsed, true
}

// SetFieldsUsed sets field value
func (o *ActionProposalInputEvidenceInner) SetFieldsUsed(v []string) {
	o.FieldsUsed = v
}

// GetActionIndex returns the ActionIndex field value if set, zero value otherwise.
func (o *ActionProposalInputEvidenceInner) GetActionIndex() int32 {
	if o == nil || IsNil(o.ActionIndex) {
		var ret int32
		return ret
	}
	return *o.ActionIndex
}

// GetActionIndexOk returns a tuple with the ActionIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActionProposalInputEvidenceInner) GetActionIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.ActionIndex) {
		return nil, false
	}
	return o.ActionIndex, true
}

// HasActionIndex returns a boolean if a field has been set.
func (o *ActionProposalInputEvidenceInner) HasActionIndex() bool {
	if o != nil && !IsNil(o.ActionIndex) {
		return true
	}

	return false
}

// SetActionIndex gets a reference to the given int32 and assigns it to the ActionIndex field.
func (o *ActionProposalInputEvidenceInner) SetActionIndex(v int32) {
	o.ActionIndex = &v
}

func (o ActionProposalInputEvidenceInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActionProposalInputEvidenceInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["source_tool"] = o.SourceTool
	toSerialize["fields_used"] = o.FieldsUsed
	if !IsNil(o.ActionIndex) {
		toSerialize["action_index"] = o.ActionIndex
	}
	return toSerialize, nil
}

func (o *ActionProposalInputEvidenceInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"source_tool",
		"fields_used",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varActionProposalInputEvidenceInner := _ActionProposalInputEvidenceInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varActionProposalInputEvidenceInner)

	if err != nil {
		return err
	}

	*o = ActionProposalInputEvidenceInner(varActionProposalInputEvidenceInner)

	return err
}

type NullableActionProposalInputEvidenceInner struct {
	value *ActionProposalInputEvidenceInner
	isSet bool
}

func (v NullableActionProposalInputEvidenceInner) Get() *ActionProposalInputEvidenceInner {
	return v.value
}

func (v *NullableActionProposalInputEvidenceInner) Set(val *ActionProposalInputEvidenceInner) {
	v.value = val
	v.isSet = true
}

func (v NullableActionProposalInputEvidenceInner) IsSet() bool {
	return v.isSet
}

func (v *NullableActionProposalInputEvidenceInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActionProposalInputEvidenceInner(val *ActionProposalInputEvidenceInner) *NullableActionProposalInputEvidenceInner {
	return &NullableActionProposalInputEvidenceInner{value: val, isSet: true}
}

func (v NullableActionProposalInputEvidenceInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActionProposalInputEvidenceInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
