/*
PlainRouter Conversion API

PlainRouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ReplayDeliveriesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReplayDeliveriesRequest{}

// ReplayDeliveriesRequest struct for ReplayDeliveriesRequest
type ReplayDeliveriesRequest struct {
	DeliveryIds          []int32        `json:"delivery_ids,omitempty"`
	EventName            NullableString `json:"event_name,omitempty"`
	Limit                NullableInt32  `json:"limit,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ReplayDeliveriesRequest ReplayDeliveriesRequest

// NewReplayDeliveriesRequest instantiates a new ReplayDeliveriesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReplayDeliveriesRequest() *ReplayDeliveriesRequest {
	this := ReplayDeliveriesRequest{}
	return &this
}

// NewReplayDeliveriesRequestWithDefaults instantiates a new ReplayDeliveriesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReplayDeliveriesRequestWithDefaults() *ReplayDeliveriesRequest {
	this := ReplayDeliveriesRequest{}
	return &this
}

// GetDeliveryIds returns the DeliveryIds field value if set, zero value otherwise.
func (o *ReplayDeliveriesRequest) GetDeliveryIds() []int32 {
	if o == nil || IsNil(o.DeliveryIds) {
		var ret []int32
		return ret
	}
	return o.DeliveryIds
}

// GetDeliveryIdsOk returns a tuple with the DeliveryIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReplayDeliveriesRequest) GetDeliveryIdsOk() ([]int32, bool) {
	if o == nil || IsNil(o.DeliveryIds) {
		return nil, false
	}
	return o.DeliveryIds, true
}

// HasDeliveryIds returns a boolean if a field has been set.
func (o *ReplayDeliveriesRequest) HasDeliveryIds() bool {
	if o != nil && !IsNil(o.DeliveryIds) {
		return true
	}

	return false
}

// SetDeliveryIds gets a reference to the given []int32 and assigns it to the DeliveryIds field.
func (o *ReplayDeliveriesRequest) SetDeliveryIds(v []int32) {
	o.DeliveryIds = v
}

// GetEventName returns the EventName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReplayDeliveriesRequest) GetEventName() string {
	if o == nil || IsNil(o.EventName.Get()) {
		var ret string
		return ret
	}
	return *o.EventName.Get()
}

// GetEventNameOk returns a tuple with the EventName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReplayDeliveriesRequest) GetEventNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EventName.Get(), o.EventName.IsSet()
}

// HasEventName returns a boolean if a field has been set.
func (o *ReplayDeliveriesRequest) HasEventName() bool {
	if o != nil && o.EventName.IsSet() {
		return true
	}

	return false
}

// SetEventName gets a reference to the given NullableString and assigns it to the EventName field.
func (o *ReplayDeliveriesRequest) SetEventName(v string) {
	o.EventName.Set(&v)
}

// SetEventNameNil sets the value for EventName to be an explicit nil
func (o *ReplayDeliveriesRequest) SetEventNameNil() {
	o.EventName.Set(nil)
}

// UnsetEventName ensures that no value is present for EventName, not even an explicit nil
func (o *ReplayDeliveriesRequest) UnsetEventName() {
	o.EventName.Unset()
}

// GetLimit returns the Limit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReplayDeliveriesRequest) GetLimit() int32 {
	if o == nil || IsNil(o.Limit.Get()) {
		var ret int32
		return ret
	}
	return *o.Limit.Get()
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReplayDeliveriesRequest) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Limit.Get(), o.Limit.IsSet()
}

// HasLimit returns a boolean if a field has been set.
func (o *ReplayDeliveriesRequest) HasLimit() bool {
	if o != nil && o.Limit.IsSet() {
		return true
	}

	return false
}

// SetLimit gets a reference to the given NullableInt32 and assigns it to the Limit field.
func (o *ReplayDeliveriesRequest) SetLimit(v int32) {
	o.Limit.Set(&v)
}

// SetLimitNil sets the value for Limit to be an explicit nil
func (o *ReplayDeliveriesRequest) SetLimitNil() {
	o.Limit.Set(nil)
}

// UnsetLimit ensures that no value is present for Limit, not even an explicit nil
func (o *ReplayDeliveriesRequest) UnsetLimit() {
	o.Limit.Unset()
}

func (o ReplayDeliveriesRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReplayDeliveriesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeliveryIds) {
		toSerialize["delivery_ids"] = o.DeliveryIds
	}
	if o.EventName.IsSet() {
		toSerialize["event_name"] = o.EventName.Get()
	}
	if o.Limit.IsSet() {
		toSerialize["limit"] = o.Limit.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReplayDeliveriesRequest) UnmarshalJSON(data []byte) (err error) {
	varReplayDeliveriesRequest := _ReplayDeliveriesRequest{}

	err = json.Unmarshal(data, &varReplayDeliveriesRequest)

	if err != nil {
		return err
	}

	*o = ReplayDeliveriesRequest(varReplayDeliveriesRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "delivery_ids")
		delete(additionalProperties, "event_name")
		delete(additionalProperties, "limit")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReplayDeliveriesRequest struct {
	value *ReplayDeliveriesRequest
	isSet bool
}

func (v NullableReplayDeliveriesRequest) Get() *ReplayDeliveriesRequest {
	return v.value
}

func (v *NullableReplayDeliveriesRequest) Set(val *ReplayDeliveriesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableReplayDeliveriesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableReplayDeliveriesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReplayDeliveriesRequest(val *ReplayDeliveriesRequest) *NullableReplayDeliveriesRequest {
	return &NullableReplayDeliveriesRequest{value: val, isSet: true}
}

func (v NullableReplayDeliveriesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReplayDeliveriesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
