/*
Plainrouter Conversion API

Plainrouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ActionProposalInputActionsInnerAnyOf4TargetEntity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActionProposalInputActionsInnerAnyOf4TargetEntity{}

// ActionProposalInputActionsInnerAnyOf4TargetEntity struct for ActionProposalInputActionsInnerAnyOf4TargetEntity
type ActionProposalInputActionsInnerAnyOf4TargetEntity struct {
	Type string         `json:"type"`
	Id   string         `json:"id"`
	Name NullableString `json:"name,omitempty"`
}

type _ActionProposalInputActionsInnerAnyOf4TargetEntity ActionProposalInputActionsInnerAnyOf4TargetEntity

// NewActionProposalInputActionsInnerAnyOf4TargetEntity instantiates a new ActionProposalInputActionsInnerAnyOf4TargetEntity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActionProposalInputActionsInnerAnyOf4TargetEntity(type_ string, id string) *ActionProposalInputActionsInnerAnyOf4TargetEntity {
	this := ActionProposalInputActionsInnerAnyOf4TargetEntity{}
	this.Type = type_
	this.Id = id
	return &this
}

// NewActionProposalInputActionsInnerAnyOf4TargetEntityWithDefaults instantiates a new ActionProposalInputActionsInnerAnyOf4TargetEntity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActionProposalInputActionsInnerAnyOf4TargetEntityWithDefaults() *ActionProposalInputActionsInnerAnyOf4TargetEntity {
	this := ActionProposalInputActionsInnerAnyOf4TargetEntity{}
	return &this
}

// GetType returns the Type field value
func (o *ActionProposalInputActionsInnerAnyOf4TargetEntity) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ActionProposalInputActionsInnerAnyOf4TargetEntity) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ActionProposalInputActionsInnerAnyOf4TargetEntity) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *ActionProposalInputActionsInnerAnyOf4TargetEntity) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ActionProposalInputActionsInnerAnyOf4TargetEntity) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ActionProposalInputActionsInnerAnyOf4TargetEntity) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ActionProposalInputActionsInnerAnyOf4TargetEntity) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ActionProposalInputActionsInnerAnyOf4TargetEntity) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *ActionProposalInputActionsInnerAnyOf4TargetEntity) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *ActionProposalInputActionsInnerAnyOf4TargetEntity) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *ActionProposalInputActionsInnerAnyOf4TargetEntity) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *ActionProposalInputActionsInnerAnyOf4TargetEntity) UnsetName() {
	o.Name.Unset()
}

func (o ActionProposalInputActionsInnerAnyOf4TargetEntity) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActionProposalInputActionsInnerAnyOf4TargetEntity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	return toSerialize, nil
}

func (o *ActionProposalInputActionsInnerAnyOf4TargetEntity) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varActionProposalInputActionsInnerAnyOf4TargetEntity := _ActionProposalInputActionsInnerAnyOf4TargetEntity{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varActionProposalInputActionsInnerAnyOf4TargetEntity)

	if err != nil {
		return err
	}

	*o = ActionProposalInputActionsInnerAnyOf4TargetEntity(varActionProposalInputActionsInnerAnyOf4TargetEntity)

	return err
}

type NullableActionProposalInputActionsInnerAnyOf4TargetEntity struct {
	value *ActionProposalInputActionsInnerAnyOf4TargetEntity
	isSet bool
}

func (v NullableActionProposalInputActionsInnerAnyOf4TargetEntity) Get() *ActionProposalInputActionsInnerAnyOf4TargetEntity {
	return v.value
}

func (v *NullableActionProposalInputActionsInnerAnyOf4TargetEntity) Set(val *ActionProposalInputActionsInnerAnyOf4TargetEntity) {
	v.value = val
	v.isSet = true
}

func (v NullableActionProposalInputActionsInnerAnyOf4TargetEntity) IsSet() bool {
	return v.isSet
}

func (v *NullableActionProposalInputActionsInnerAnyOf4TargetEntity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActionProposalInputActionsInnerAnyOf4TargetEntity(val *ActionProposalInputActionsInnerAnyOf4TargetEntity) *NullableActionProposalInputActionsInnerAnyOf4TargetEntity {
	return &NullableActionProposalInputActionsInnerAnyOf4TargetEntity{value: val, isSet: true}
}

func (v NullableActionProposalInputActionsInnerAnyOf4TargetEntity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActionProposalInputActionsInnerAnyOf4TargetEntity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
