/*
Plainrouter Conversion API

Plainrouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ActionProposalInputActionsInnerAnyOf8 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActionProposalInputActionsInnerAnyOf8{}

// ActionProposalInputActionsInnerAnyOf8 struct for ActionProposalInputActionsInnerAnyOf8
type ActionProposalInputActionsInnerAnyOf8 struct {
	Type                 string                                            `json:"type"`
	TargetEntity         ActionProposalInputActionsInnerAnyOf4TargetEntity `json:"target_entity"`
	Params               map[string]interface{}                            `json:"params"`
	Rationale            string                                            `json:"rationale"`
	IdempotencyKey       *string                                           `json:"idempotency_key,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ActionProposalInputActionsInnerAnyOf8 ActionProposalInputActionsInnerAnyOf8

// NewActionProposalInputActionsInnerAnyOf8 instantiates a new ActionProposalInputActionsInnerAnyOf8 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActionProposalInputActionsInnerAnyOf8(type_ string, targetEntity ActionProposalInputActionsInnerAnyOf4TargetEntity, params map[string]interface{}, rationale string) *ActionProposalInputActionsInnerAnyOf8 {
	this := ActionProposalInputActionsInnerAnyOf8{}
	this.Type = type_
	this.TargetEntity = targetEntity
	this.Params = params
	this.Rationale = rationale
	return &this
}

// NewActionProposalInputActionsInnerAnyOf8WithDefaults instantiates a new ActionProposalInputActionsInnerAnyOf8 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActionProposalInputActionsInnerAnyOf8WithDefaults() *ActionProposalInputActionsInnerAnyOf8 {
	this := ActionProposalInputActionsInnerAnyOf8{}
	return &this
}

// GetType returns the Type field value
func (o *ActionProposalInputActionsInnerAnyOf8) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ActionProposalInputActionsInnerAnyOf8) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ActionProposalInputActionsInnerAnyOf8) SetType(v string) {
	o.Type = v
}

// GetTargetEntity returns the TargetEntity field value
func (o *ActionProposalInputActionsInnerAnyOf8) GetTargetEntity() ActionProposalInputActionsInnerAnyOf4TargetEntity {
	if o == nil {
		var ret ActionProposalInputActionsInnerAnyOf4TargetEntity
		return ret
	}

	return o.TargetEntity
}

// GetTargetEntityOk returns a tuple with the TargetEntity field value
// and a boolean to check if the value has been set.
func (o *ActionProposalInputActionsInnerAnyOf8) GetTargetEntityOk() (*ActionProposalInputActionsInnerAnyOf4TargetEntity, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetEntity, true
}

// SetTargetEntity sets field value
func (o *ActionProposalInputActionsInnerAnyOf8) SetTargetEntity(v ActionProposalInputActionsInnerAnyOf4TargetEntity) {
	o.TargetEntity = v
}

// GetParams returns the Params field value
func (o *ActionProposalInputActionsInnerAnyOf8) GetParams() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Params
}

// GetParamsOk returns a tuple with the Params field value
// and a boolean to check if the value has been set.
func (o *ActionProposalInputActionsInnerAnyOf8) GetParamsOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Params, true
}

// SetParams sets field value
func (o *ActionProposalInputActionsInnerAnyOf8) SetParams(v map[string]interface{}) {
	o.Params = v
}

// GetRationale returns the Rationale field value
func (o *ActionProposalInputActionsInnerAnyOf8) GetRationale() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Rationale
}

// GetRationaleOk returns a tuple with the Rationale field value
// and a boolean to check if the value has been set.
func (o *ActionProposalInputActionsInnerAnyOf8) GetRationaleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rationale, true
}

// SetRationale sets field value
func (o *ActionProposalInputActionsInnerAnyOf8) SetRationale(v string) {
	o.Rationale = v
}

// GetIdempotencyKey returns the IdempotencyKey field value if set, zero value otherwise.
func (o *ActionProposalInputActionsInnerAnyOf8) GetIdempotencyKey() string {
	if o == nil || IsNil(o.IdempotencyKey) {
		var ret string
		return ret
	}
	return *o.IdempotencyKey
}

// GetIdempotencyKeyOk returns a tuple with the IdempotencyKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActionProposalInputActionsInnerAnyOf8) GetIdempotencyKeyOk() (*string, bool) {
	if o == nil || IsNil(o.IdempotencyKey) {
		return nil, false
	}
	return o.IdempotencyKey, true
}

// HasIdempotencyKey returns a boolean if a field has been set.
func (o *ActionProposalInputActionsInnerAnyOf8) HasIdempotencyKey() bool {
	if o != nil && !IsNil(o.IdempotencyKey) {
		return true
	}

	return false
}

// SetIdempotencyKey gets a reference to the given string and assigns it to the IdempotencyKey field.
func (o *ActionProposalInputActionsInnerAnyOf8) SetIdempotencyKey(v string) {
	o.IdempotencyKey = &v
}

func (o ActionProposalInputActionsInnerAnyOf8) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActionProposalInputActionsInnerAnyOf8) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["target_entity"] = o.TargetEntity
	toSerialize["params"] = o.Params
	toSerialize["rationale"] = o.Rationale
	if !IsNil(o.IdempotencyKey) {
		toSerialize["idempotency_key"] = o.IdempotencyKey
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ActionProposalInputActionsInnerAnyOf8) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"target_entity",
		"params",
		"rationale",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varActionProposalInputActionsInnerAnyOf8 := _ActionProposalInputActionsInnerAnyOf8{}

	err = json.Unmarshal(data, &varActionProposalInputActionsInnerAnyOf8)

	if err != nil {
		return err
	}

	*o = ActionProposalInputActionsInnerAnyOf8(varActionProposalInputActionsInnerAnyOf8)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "target_entity")
		delete(additionalProperties, "params")
		delete(additionalProperties, "rationale")
		delete(additionalProperties, "idempotency_key")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableActionProposalInputActionsInnerAnyOf8 struct {
	value *ActionProposalInputActionsInnerAnyOf8
	isSet bool
}

func (v NullableActionProposalInputActionsInnerAnyOf8) Get() *ActionProposalInputActionsInnerAnyOf8 {
	return v.value
}

func (v *NullableActionProposalInputActionsInnerAnyOf8) Set(val *ActionProposalInputActionsInnerAnyOf8) {
	v.value = val
	v.isSet = true
}

func (v NullableActionProposalInputActionsInnerAnyOf8) IsSet() bool {
	return v.isSet
}

func (v *NullableActionProposalInputActionsInnerAnyOf8) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActionProposalInputActionsInnerAnyOf8(val *ActionProposalInputActionsInnerAnyOf8) *NullableActionProposalInputActionsInnerAnyOf8 {
	return &NullableActionProposalInputActionsInnerAnyOf8{value: val, isSet: true}
}

func (v NullableActionProposalInputActionsInnerAnyOf8) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActionProposalInputActionsInnerAnyOf8) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
