/*
Plainrouter Conversion API

Plainrouter public Signals Conversion API.

API version: 0.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GetSandbox200ResponseSelfServeKeyIssuedKeyUse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSandbox200ResponseSelfServeKeyIssuedKeyUse{}

// GetSandbox200ResponseSelfServeKeyIssuedKeyUse struct for GetSandbox200ResponseSelfServeKeyIssuedKeyUse
type GetSandbox200ResponseSelfServeKeyIssuedKeyUse struct {
	Method               string `json:"method"`
	Url                  string `json:"url"`
	Authorization        string `json:"authorization"`
	AdditionalProperties map[string]interface{}
}

type _GetSandbox200ResponseSelfServeKeyIssuedKeyUse GetSandbox200ResponseSelfServeKeyIssuedKeyUse

// NewGetSandbox200ResponseSelfServeKeyIssuedKeyUse instantiates a new GetSandbox200ResponseSelfServeKeyIssuedKeyUse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSandbox200ResponseSelfServeKeyIssuedKeyUse(method string, url string, authorization string) *GetSandbox200ResponseSelfServeKeyIssuedKeyUse {
	this := GetSandbox200ResponseSelfServeKeyIssuedKeyUse{}
	this.Method = method
	this.Url = url
	this.Authorization = authorization
	return &this
}

// NewGetSandbox200ResponseSelfServeKeyIssuedKeyUseWithDefaults instantiates a new GetSandbox200ResponseSelfServeKeyIssuedKeyUse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSandbox200ResponseSelfServeKeyIssuedKeyUseWithDefaults() *GetSandbox200ResponseSelfServeKeyIssuedKeyUse {
	this := GetSandbox200ResponseSelfServeKeyIssuedKeyUse{}
	return &this
}

// GetMethod returns the Method field value
func (o *GetSandbox200ResponseSelfServeKeyIssuedKeyUse) GetMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Method
}

// GetMethodOk returns a tuple with the Method field value
// and a boolean to check if the value has been set.
func (o *GetSandbox200ResponseSelfServeKeyIssuedKeyUse) GetMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Method, true
}

// SetMethod sets field value
func (o *GetSandbox200ResponseSelfServeKeyIssuedKeyUse) SetMethod(v string) {
	o.Method = v
}

// GetUrl returns the Url field value
func (o *GetSandbox200ResponseSelfServeKeyIssuedKeyUse) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *GetSandbox200ResponseSelfServeKeyIssuedKeyUse) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *GetSandbox200ResponseSelfServeKeyIssuedKeyUse) SetUrl(v string) {
	o.Url = v
}

// GetAuthorization returns the Authorization field value
func (o *GetSandbox200ResponseSelfServeKeyIssuedKeyUse) GetAuthorization() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Authorization
}

// GetAuthorizationOk returns a tuple with the Authorization field value
// and a boolean to check if the value has been set.
func (o *GetSandbox200ResponseSelfServeKeyIssuedKeyUse) GetAuthorizationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Authorization, true
}

// SetAuthorization sets field value
func (o *GetSandbox200ResponseSelfServeKeyIssuedKeyUse) SetAuthorization(v string) {
	o.Authorization = v
}

func (o GetSandbox200ResponseSelfServeKeyIssuedKeyUse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSandbox200ResponseSelfServeKeyIssuedKeyUse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["method"] = o.Method
	toSerialize["url"] = o.Url
	toSerialize["authorization"] = o.Authorization

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetSandbox200ResponseSelfServeKeyIssuedKeyUse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"method",
		"url",
		"authorization",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetSandbox200ResponseSelfServeKeyIssuedKeyUse := _GetSandbox200ResponseSelfServeKeyIssuedKeyUse{}

	err = json.Unmarshal(data, &varGetSandbox200ResponseSelfServeKeyIssuedKeyUse)

	if err != nil {
		return err
	}

	*o = GetSandbox200ResponseSelfServeKeyIssuedKeyUse(varGetSandbox200ResponseSelfServeKeyIssuedKeyUse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "method")
		delete(additionalProperties, "url")
		delete(additionalProperties, "authorization")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetSandbox200ResponseSelfServeKeyIssuedKeyUse struct {
	value *GetSandbox200ResponseSelfServeKeyIssuedKeyUse
	isSet bool
}

func (v NullableGetSandbox200ResponseSelfServeKeyIssuedKeyUse) Get() *GetSandbox200ResponseSelfServeKeyIssuedKeyUse {
	return v.value
}

func (v *NullableGetSandbox200ResponseSelfServeKeyIssuedKeyUse) Set(val *GetSandbox200ResponseSelfServeKeyIssuedKeyUse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSandbox200ResponseSelfServeKeyIssuedKeyUse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSandbox200ResponseSelfServeKeyIssuedKeyUse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSandbox200ResponseSelfServeKeyIssuedKeyUse(val *GetSandbox200ResponseSelfServeKeyIssuedKeyUse) *NullableGetSandbox200ResponseSelfServeKeyIssuedKeyUse {
	return &NullableGetSandbox200ResponseSelfServeKeyIssuedKeyUse{value: val, isSet: true}
}

func (v NullableGetSandbox200ResponseSelfServeKeyIssuedKeyUse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSandbox200ResponseSelfServeKeyIssuedKeyUse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
